Major CLI Updates
- Removed slow Travis CI with powerful Github Action Workflow.
- Added initially Pi[0-1] builder workflow config yaml file.
- Renamed builder script.
- Other Minor Fixes.

diff --git a/build-scripts/CLI/CLICTB_64b b/build-scripts/CLI/CLICTB_64b
--- a/build-scripts/CLI/CLICTB_64b
+++ b/build-scripts/CLI/CLICTB_64b
@@ -26,9 +26,8 @@
 
 
 
-# This script auto downloads, compiles, and compresses Cross & Native GCC ARM Toolchain binaries 
-# targeting Raspberry Pi 32-bit Stretch(Debian 9) and Buster(Debian 10) OSes only.
-
+# This script aauto downloads, compiles, and compresses Cross & Native GCC ARM64 Toolchain 
+# binaries targeting any Raspberry Pi 64-bit (like Pi64) OSes.
 
 
 helpfunction()
@@ -36,141 +35,98 @@ helpfunction()
    #helper function that prints custom usage help menu
    echo ""
    echo ""
-   figlet -t -k -f /usr/share/figlet/standard.flf "CLI Raspberry Pi Cross Toolchains Builder 32-bit"
+   figlet -t -k -f /usr/share/figlet/standard.flf "CLI Raspberry Pi Cross Toolchains Builder 64-bit"
    echo ""
    figlet -t -k -f /usr/share/figlet/term.flf "Copyright (c) 2020 abhiTronix"
    echo ""
    echo ""
-   echo "Usage: $0 -g [GCC version] -r [Target Pi type] -o [Target Pi OS type]"
+   echo "Usage: $0 -g [GCC version] -t [Target OS type]"
    echo -e "\t-g GCC version you want to compile?: (7.1.0|7.2.0|7.3.0|7.4.0|7.5.0|8.1.0|8.2.0|8.3.0|9.1.0|9.2.0)"
-   echo -e "\t-r What's yours Target Raspberry Pi type?: (0-1|2-3|3+)"
-   echo -e "\t-o What's yours Target Raspberry Pi OS type?: (stretch|buster)"
+   echo -e "\t-t What's yours Target OS type?: (1|2) [default:1]"
    echo ""
    echo ""
-   exit 1 # Exit script after printing help
+   exit 1 # Exits script after printing help
 }
 
 
 
 #input arguments handler
-while getopts "g:r:o:" opt
+while getopts "g:t:" opt
 do
    case "$opt" in
    	  g ) GCC_VERSION="$OPTARG" ;;
-      r ) RPI_TYPE="$OPTARG" ;;
-      o ) RPIOS_TYPE="$OPTARG" ;;
+      t ) OS_TYPE="$OPTARG" ;;
       ? ) helpfunction ;; #prints help function for invalid parameter
    esac
 done
 #validates parameters and print usage helper function in case parameters are missing
-if [ -z "$GCC_VERSION" ] || [ -z "$RPI_TYPE" ] || [ -z "$RPIOS_TYPE" ]
-then
-   echo "Error: Required parameters are missing!";
+if [ -z "$GCC_VERSION" ]; then
+   echo "Error: Required parameter is missing!";
    helpfunction
-fi
-
-
-
-#collect parameters from raspbery pi type
-if [ "$RPI_TYPE" = "2-3" ]; then
-	FOLDER_VERSION=1
-	ARCH=armv7-a
-	FPU=neon-vfpv4;
-elif [ "$RPI_TYPE" = "3+" ]; then
-	FOLDER_VERSION=2
-	ARCH=armv8-a
-	FPU=neon-fp-armv8
-elif [ "$RPI_TYPE" = "0-1" ]; then
-	FOLDER_VERSION=0
-	ARCH=armv6
-	FPU=vfp
+elif [ -z "$OS_TYPE" ]; then
+	OS_TYPE=1
 else
-	echo "Invalid argument value: $RPI_TYPE"
-	exit
+	echo "Parameters configured!";
 fi
+
 
 #collect dependencies versions from raspberry pi os
-if [ "$RPIOS_TYPE" = "stretch" ] || [ "$GCC_VERSION" \< "8.3.0" ]; then
+if [ "$OS_TYPE" = "1" ] || [ "$GCC_VERSION" \< "8.3.0" ] ; then
 	GCCBASE_VERSION=6.3.0
-elif [ "$RPIOS_TYPE" = "buster" ]; then
+elif [ "$OS_TYPE" = "2" ]; then
 	GCCBASE_VERSION=8.3.0
 else
-	echo "Invalid argument value: $RPIOS_TYPE"
+	echo "Invalid argument value: $OS_TYPE"
 	exit
 fi
+
 
 #collect build directory if not defined
 if [ "$BUILDDIR" = "" ]; then
-	#select temp directory as default
+	#select temp directory
 	echo "Build directory is empty, using temp directory!"
 	BUILDDIR=$(dirname "$(mktemp tmp.XXXXXXXXXX -ut)")
 fi
 
 #collect programming languages if not defined
 if [ "$LANGUAGES" = "" ]; then
-	#select `c,c++,fortran` as default
+	#select temp directory
 	echo "Building binaries for c,c++,fortran programming languages!"
 	LANGUAGES=c,c++,fortran
 fi
 
+
 #pre-defined params
-TARGET=arm-linux-gnueabihf
+FOLDER_VERSION=64
+ARCH=armv8-a+fp+simd
+TARGET=aarch64-linux-gnu
 GDB_VERSION=8.3.1
+
 
 #validate env variables
 if ! [[ "$GCC_VERSION" =~ ^(7.1.0|7.2.0|7.3.0|7.4.0|7.5.0|8.1.0|8.2.0|8.3.0|9.1.0|9.2.0)$ ]]; then exit 1 ; fi
 if ! [[ "$GCCBASE_VERSION" =~ ^(6.3.0|8.3.0)$ ]]; then exit 1 ; fi
-if ! [[ "$FOLDER_VERSION" =~ ^(0|1|2)$ ]]; then exit 1 ; fi
-if ! [[ "$ARCH" =~ ^(armv6|armv7-a|armv8-a)$ ]]; then exit 1 ; fi
-if ! [[ "$FPU" =~ ^(vfp|neon-vfpv4|neon-fp-armv8)$ ]]; then exit 1 ; fi
+if [ "$ARCH" != "armv8-a+fp+simd" ]; then exit 1 ; fi
+if [ "$FOLDER_VERSION" != "64" ]; then exit 1 ; fi
 if [ "$BUILDDIR" = "" ]; then exit 1 ; fi
 if [ "$LANGUAGES" = "" ]; then exit 1 ; fi
 
-
 URL="https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/CLI%20Base"
+if [ "$RPI_TYPE" = "64" ]; then URL="$URL/64/GCC%20$GCCBASE_VERSION/"; fi
 
-if [ "$RPIOS_TYPE" = "buster" ]; then
-	URL="$URL/Buster/GCC%20$GCCBASE_VERSION"
-	if [ "$RPI_TYPE" = "0-1" ]; then
-		URL="$URL/Raspberry%20Pi%201%2C%20Zero/"
-	elif [ "$RPI_TYPE" = "2-3" ]; then
-		URL="$URL/Raspberry%20Pi%202%2C%203/"
-	elif [ "$RPI_TYPE" = "3+" ]; then
-		URL="$URL/Raspberry%20Pi%203A%2B%2C%203B%2B%2C%204/"
-	else
-		echo "Missing RPI_TYPE parameter!"
-		exit 1;
-	fi
-elif [ "$RPIOS_TYPE" = "stretch" ]; then
-	URL="$URL/Stretch/GCC%20$GCCBASE_VERSION"
-	if [ "$RPI_TYPE" = "0-1" ]; then
-		URL="$URL/Raspberry%20Pi%201%2C%20Zero/"
-	elif [ "$RPI_TYPE" = "2-3" ]; then
-		URL="$URL/Raspberry%20Pi%202%2C%203/"
-	elif [ "$RPI_TYPE" = "3+" ]; then
-		URL="$URL/Raspberry%20Pi%203A%2B%2C%203B%2B%2C%204/"
-	else
-		echo "Missing RPI_TYPE parameter!"
-		exit 1;
-	fi
-else 
-	echo "Missing RPIOS_TYPE parameter!"
-	exit 1;
-fi
-
-
-#download binaries if not found
 echo "Downloading and Setting up build directories"
-
+#setup paths
 DOWNLOADDIR=$BUILDDIR/build_toolchains
 INSTALLDIR=$BUILDDIR/cross-pi-gcc-$GCC_VERSION-$FOLDER_VERSION
 SYSROOTDIR=$BUILDDIR/cross-pi-gcc-$GCC_VERSION-$FOLDER_VERSION/$TARGET/libc
 
+#make dirs
 mkdir -p "$DOWNLOADDIR"
 mkdir -p "$INSTALLDIR"
 
 cd "$DOWNLOADDIR" || exit
 
+#download binaries if not found
 if [ ! -d "gcc-$GCCBASE_VERSION" ]; then
 	if [ ! -f "cross-gcc-$GCCBASE_VERSION-pi_$RPI_TYPE.tar.gz" ]; then wget -q "${URL}cross-gcc-$GCCBASE_VERSION-pi_$RPI_TYPE.tar.gz"; fi
 	tar xf cross-gcc-$GCCBASE_VERSION-pi_$RPI_TYPE.tar.gz
@@ -179,7 +135,9 @@ if [ ! -d "gcc-$GCCBASE_VERSION" ]; then
 	rm ./*.tar.*
 fi
 if [ ! -d "gdb-$GDB_VERSION" ]; then
-	if [ ! -f "gdb-$GDB_VERSION.tar.xz" ]; then wget -q https://ftp.gnu.org/gnu/gdb/gdb-$GDB_VERSION.tar.xz; fi
+	if [ ! -f "gdb-$GDB_VERSION.tar.xz" ]; then 
+		wget -q https://ftp.gnu.org/gnu/gdb/gdb-$GDB_VERSION.tar.xz; 
+	fi
 	tar xf  gdb-$GDB_VERSION.tar.xz
 	cd gdb-$GDB_VERSION || exit
 	mkdir -p build 
@@ -187,10 +145,12 @@ if [ ! -d "gdb-$GDB_VERSION" ]; then
 	rm ./*.tar.*
 fi
 if [ ! -d "gcc-$GCC_VERSION" ]; then
-	if [ ! -f "gcc-$GCC_VERSION.tar.gz" ]; then wget -q https://ftpmirror.gnu.org/gcc/gcc-"$GCC_VERSION"/gcc-"$GCC_VERSION".tar.gz; fi
+	if [ ! -f "gcc-$GCC_VERSION.tar.gz" ]; then 
+		wget -q  https://ftpmirror.gnu.org/gcc/gcc-"$GCC_VERSION"/gcc-"$GCC_VERSION".tar.gz; 
+	fi
 	tar xf gcc-"$GCC_VERSION".tar.gz
 	cd gcc-"$GCC_VERSION" || exit
-	mkdir -p build
+	mkdir -p build 
 	sed -i contrib/download_prerequisites -e '/base_url=/s/ftp/http/'
 	contrib/download_prerequisites
 	rm ./*.tar.*
@@ -198,15 +158,15 @@ if [ ! -d "gcc-$GCC_VERSION" ]; then
 	rm ./*.tar.*
 fi
 
-
 echo "Setting up paths..."
 PATH=$BUILDDIR/cross-pi-gcc-$GCC_VERSION-$FOLDER_VERSION/bin:$PATH
 unset LD_LIBRARY_PATH #patch
 
+
 if [ "$GCC_VERSION" != "$GCCBASE_VERSION" ]; then
 	cd "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build || exit
 	if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build/*; fi
-	../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH  --with-fpu=$FPU --with-float=hard  --disable-multilib
+	../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH   --disable-multilib
 	make -s -j$(nproc)
 	make -s install DESTDIR="$INSTALLDIR"
 	if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build/*; fi
@@ -217,17 +177,17 @@ cat gcc/limitx.h gcc/glimits.h gcc/limity.h > $(dirname $($TARGET-gcc -print-lib
 
 echo "Building Cross GDB Binaries..."
 cd "$DOWNLOADDIR"/gdb-$GDB_VERSION/build || exit
-if [ -n "$(ls -A "$DOWNLOADDIR"/gdb-$GDB_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gdb-$GDB_VERSION/build/*; fi #cleanup
-../configure --prefix= --target=$TARGET --with-arch=$ARCH  --with-fpu=$FPU --with-float=hard
+if [ -n "$(ls -A "$DOWNLOADDIR"/gdb-$GDB_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gdb-$GDB_VERSION/build/*; fi
+../configure --prefix= --target=$TARGET --with-arch=$ARCH  --with-float=hard
 make -s -j$(nproc)
 make -s install DESTDIR="$INSTALLDIR"
-if [ -n "$(ls -A "$DOWNLOADDIR"/gdb-$GDB_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gdb-$GDB_VERSION/build/*; fi #cleanup
+if [ -n "$(ls -A "$DOWNLOADDIR"/gdb-$GDB_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gdb-$GDB_VERSION/build/*; fi
 echo "Done Building Cross GDB Binaries..."
 
 mv "$BUILDDIR"/cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION "$HOME"
 cd "$HOME" || exit
 #compress with maximum possible compression level.
-env GZIP=-9 tar cvzf cross-gcc-"$GCC_VERSION"-pi_"$RPI_TYPE".tar.gz cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION
+tar cf - cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 > cross-gcc-"$GCC_VERSION"-pi_"$RPI_TYPE".tar.gz 
 echo "Done Building Cross GCC $GCC_VERSION Binaries..."
 rm -rf "$HOME"/cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION
 
