Update CI build scripts for newer GCC versions and OSes
- Add support for GCC 11.x, 12.x, 13.x and 14.x versions
- Add support for Debian Bookworm (12)
- Remove support for Debian Stretch (9)
- Update GDB version to 15.1
- Adjust OS and GCC version compatibility checks
- Clean up temporary files more thoroughly
- Update README with new supported versions and OSes
- Minor code cleanup and standardization across scripts

diff --git a/build-scripts/CI/CIBB_32b b/build-scripts/CI/CIBB_32b
--- a/build-scripts/CI/CIBB_32b
+++ b/build-scripts/CI/CIBB_32b
@@ -34,9 +34,9 @@ helpfunction() {
 	echo ""
 	echo ""
 	echo "Usage: $0 -g [GCC version] -r [Target Pi type] -o [Target Pi OS type]"
-	echo -e "\t-g GCC base version?: (6.3.0|8.3.0)"
+	echo -e "\t-g GCC base version?: (8.3.0|10.2.1|12.2.0)"
 	echo -e "\t-r What's yours Raspberry Pi type?: (0-1|2-3|3+)"
-	echo -e "\t-o What's yours Raspberry Pi OS type?: (stretch|buster|bullseye)"
+	echo -e "\t-o What's yours Raspberry Pi OS type?: (buster|bullseye|bookworm)"
 	echo ""
 	echo ""
 	exit 1 # Exit script after printing help
@@ -81,9 +81,9 @@ else
 fi
 
 #collect dependencies versions from raspberry pi os
-if [ "$RPIOS_TYPE" = "stretch" ]; then
-	GLIBC_VERSION=2.24
-	BINUTILS_VERSION=2.28
+if [ "$RPIOS_TYPE" = "bookworm" ]; then
+	GLIBC_VERSION=2.36
+	BINUTILS_VERSION=2.40
 elif [ "$RPIOS_TYPE" = "buster" ]; then
 	GLIBC_VERSION=2.28
 	BINUTILS_VERSION=2.31.1
@@ -95,8 +95,9 @@ else
 	exit
 fi
 
-if [ "$RPIOS_TYPE" = "stretch" ] && [ "$GCC_VERSION" != "6.3.0" ]; then
-	echo "Invalid GCC for stretch: $GCC_VERSION!"
+# exit if not valid GCC
+if [ "$RPIOS_TYPE" = "bookworm" ] && [ "$GCC_VERSION" != "12.2.0" ]; then
+	echo "Invalid GCC for bookworm: $GCC_VERSION!"
 	exit
 fi
 # exit if not valid GCC
@@ -105,7 +106,7 @@ if [ "$RPIOS_TYPE" = "buster" ] && [ "$GCC_VERSION" != "8.3.0" ]; then
 	exit
 fi
 # exit if not valid GCC
-if [ "$RPIOS_TYPE" = "bullseye" ] && [ "$GCC_VERSION" != "10.2.0" ]; then
+if [ "$RPIOS_TYPE" = "bullseye" ] && [ "$GCC_VERSION" != "10.2.1" ]; then
 	echo "Invalid GCC for bullseye: $GCC_VERSION!"
 	exit
 fi
@@ -126,12 +127,12 @@ fi
 
 #pre-defined params
 TARGET=arm-linux-gnueabihf
-GDB_VERSION=10.2
+GDB_VERSION=15.1
 
 #validate env variables
-if ! [[ "$GCC_VERSION" =~ ^(6.3.0|8.3.0|10.2.0)$ ]]; then exit 1; fi
-if ! [[ "$GLIBC_VERSION" =~ ^(2.24|2.28|2.31)$ ]]; then exit 1; fi
-if ! [[ "$BINUTILS_VERSION" =~ ^(2.28|2.31.1|2.35.2)$ ]]; then exit 1; fi
+if ! [[ "$GCC_VERSION" =~ ^(8.3.0|10.2.1|12.2.0)$ ]]; then exit 1; fi
+if ! [[ "$GLIBC_VERSION" =~ ^(2.28|2.31|2.36)$ ]]; then exit 1; fi
+if ! [[ "$BINUTILS_VERSION" =~ ^(2.31.1|2.35.2|2.40)$ ]]; then exit 1; fi
 if ! [[ "$FOLDER_VERSION" =~ ^(0|1|2)$ ]]; then exit 1; fi
 if ! [[ "$KERNEL" =~ ^(kernel|kernel7)$ ]]; then exit 1; fi
 if ! [[ "$ARCH" =~ ^(armv6|armv7-a|armv8-a)$ ]]; then exit 1; fi
@@ -165,16 +166,11 @@ if [ ! -d "gcc-$GCC_VERSION" ]; then
 		sed -i -e '66i#define PATH_MAX 4096\' libsanitizer/asan/asan_linux.cpp
 	fi
 	mkdir -p build
-	if [ "$GCC_VERSION" = "6.3.0" ]; then
-		sed -i contrib/download_prerequisites -e 's/ftp/http/'
-	else
-		sed -i contrib/download_prerequisites -e '/base_url=/s/ftp/http/'
-	fi
+	sed -i contrib/download_prerequisites -e '/base_url=/s/ftp/http/'
 	contrib/download_prerequisites
-	rm ./*.tar.*
-	if [ "$GCC_VERSION" = "6.3.0" ]; then sed -i "1474s/.*/      || xloc.file[0] == '\\\0' || xloc.file[0] == '\\\xff'/" ./gcc/ubsan.c; fi #apply patch
+	rm ./*.tar.* || true
 	cd "$DOWNLOADDIR" || exit
-	rm ./*.tar.*
+	rm ./*.tar.* || true
 fi
 if [ ! -d "binutils-$BINUTILS_VERSION" ]; then
 	if [ ! -f "binutils-$BINUTILS_VERSION.tar.bz2" ]; then
@@ -184,7 +180,7 @@ if [ ! -d "binutils-$BINUTILS_VERSION" ]; then
 	cd binutils-$BINUTILS_VERSION || exit
 	mkdir -p build
 	cd "$DOWNLOADDIR" || exit
-	rm ./*.tar.*
+	rm ./*.tar.* || true
 fi
 if [ ! -d "glibc-$GLIBC_VERSION" ]; then
 	# Download patched Glibc 2.31 if GCC 10 series are being built
@@ -199,8 +195,10 @@ if [ ! -d "glibc-$GLIBC_VERSION" ]; then
 	cd glibc-$GLIBC_VERSION || exit
 	mkdir -p build
 	cd "$DOWNLOADDIR" || exit
-	rm ./*.tar.*
+	rm ./*.tar.* || true
 fi
+sed -i 's/#  include <limits.h>/#  include <linux\/limits.h>/' gcc-$GCC_VERSION/libsanitizer/asan/asan_linux.cpp
+sed -i 's/#include <limits.h>/#include <linux\/limits.h>/' gcc-$GCC_VERSION/libsanitizer/asan/asan_linux.cpp
 
 echo "Setting up paths..."
 PATH=$BUILDDIR/cross-pi-gcc-$GCC_VERSION-$FOLDER_VERSION/bin:$PATH
diff --git a/build-scripts/CI/CINTB_32b b/build-scripts/CI/CINTB_32b
--- a/build-scripts/CI/CINTB_32b
+++ b/build-scripts/CI/CINTB_32b
@@ -34,9 +34,9 @@ helpfunction() {
 	echo ""
 	echo ""
 	echo "Usage: $0 -g [GCC version] -r [Target Pi type] -o [Target Pi OS type]"
-	echo -e "\t-g GCC version you want to compile?: (7.1.0|7.2.0|7.3.0|7.4.0|7.5.0|8.1.0|8.2.0|8.3.0|8.4.0|9.1.0|9.2.0|9.3.0|9.4.0|10.1.0|10.2.0|10.3.0)"
+	echo -e "\t-g GCC version you want to compile?: (8.4.0|9.1.0|9.2.0|9.3.0|9.4.0|10.1.0|10.2.0|10.3.0|11.1.0|11.2.0|11.3.0|12.1.0|12.2.0|12.3.0|12.4.0|13.1.0|13.2.0|13.3.0|14.1.0|14.2.0)"
 	echo -e "\t-r What's yours Target Raspberry Pi type?: (0-1|2-3|3+)"
-	echo -e "\t-o What's yours Target Raspberry Pi OS type?: (stretch|buster|bullseye)"
+	echo -e "\t-o What's yours Target Raspberry Pi OS type?: (buster|bullseye|bookworm)"
 	echo ""
 	echo ""
 	exit 1 # Exit script after printing help
@@ -57,24 +57,25 @@ if [ -z "$GCC_VERSION" ] || [ -z "$RPI_TYPE" ] || [ -z "$RPIOS_TYPE" ]; then
 	helpfunction
 fi
 
-# skip bullseye base
-if [ "$RPIOS_TYPE" != "bullseye" ] && [ "$GCC_VERSION" = "10.2.0" ]; then
-	echo "Invalid GCC: $GCC_VERSION!"
-	exit
-fi
-
-if [ "$RPIOS_TYPE" = "buster" ]; then
-	if echo ${GCC_VERSION%.*} "8.3" | awk '{exit ( $1 >= $2 )}'; then
+#collect dependencies versions from raspberry pi os
+if [ "$RPIOS_TYPE" = "bookworm" ]; then
+	if echo ${GCC_VERSION%.*} "12.2" | awk '{exit ( $1 > $2 )}'; then
+		echo "$GCC_VERSION is not supported on bookworm!"
+		exit 0
+	fi
+elif [ "$RPIOS_TYPE" = "buster" ]; then
+	if echo ${GCC_VERSION%.*} "8.3" | awk '{exit ( $1 > $2 )}'; then
 		echo "$GCC_VERSION is not supported on buster!"
 		exit 0
 	fi
-fi
-
-if [ "$RPIOS_TYPE" = "bullseye" ]; then
-	if echo ${GCC_VERSION%.*} "10.2" | awk '{exit ( $1 >= $2 )}'; then
+elif [ "$RPIOS_TYPE" = "bullseye" ]; then
+	if echo ${GCC_VERSION%.*} "10.2" | awk '{exit ( $1 > $2 )}'; then
 		echo "$GCC_VERSION is not supported on bullseye!"
 		exit 0
 	fi
+else
+	echo "Invalid argument value: $RPIOS_TYPE"
+	exit 1
 fi
 
 #collect parameters from raspbery pi type
@@ -111,7 +112,7 @@ fi
 
 #pre-defined params
 TARGET=arm-linux-gnueabihf
-GDB_VERSION=10.2
+GDB_VERSION=15.1
 
 #validate env variables
 if ! [[ "$FOLDER_VERSION" =~ ^(0|1|2)$ ]]; then exit 1; fi
@@ -175,7 +176,7 @@ if [ ! -f "cross-gcc-$GCC_VERSION-pi_$RPI_TYPE.tar.gz" ]; then
 	wget "${URL}cross-gcc-$GCC_VERSION-pi_$RPI_TYPE.tar.gz"
 	tar xf cross-gcc-$GCC_VERSION-pi_$RPI_TYPE.tar.gz
 	mv cross-pi-gcc-$GCC_VERSION-$FOLDER_VERSION $BUILDDIR
-	rm ./*.tar.*
+	rm ./*.tar.* || true
 fi
 if [ ! -d "gdb-$GDB_VERSION" ]; then
 	if [ ! -f "gdb-$GDB_VERSION.tar.xz" ]; then wget -q --no-check-certificate https://ftp.gnu.org/gnu/gdb/gdb-$GDB_VERSION.tar.xz; fi
@@ -183,7 +184,7 @@ if [ ! -d "gdb-$GDB_VERSION" ]; then
 	cd gdb-$GDB_VERSION || exit
 	mkdir -p build
 	cd "$DOWNLOADDIR" || exit
-	rm ./*.tar.*
+	rm ./*.tar.* || true
 fi
 if [ ! -d "gcc-$GCC_VERSION" ]; then
 	# Download patched GCC 10 series for bullseye
@@ -199,9 +200,9 @@ if [ ! -d "gcc-$GCC_VERSION" ]; then
 	mkdir -p build
 	sed -i contrib/download_prerequisites -e '/base_url=/s/ftp/http/'
 	contrib/download_prerequisites
-	rm ./*.tar.*
+	rm ./*.tar.* || true
 	cd "$DOWNLOADDIR" || exit
-	rm ./*.tar.*
+	rm ./*.tar.* || true
 fi
 
 echo "Setting up paths..."
diff --git a/build-scripts/CI/CINTB_64b b/build-scripts/CI/CINTB_64b
--- a/build-scripts/CI/CINTB_64b
+++ b/build-scripts/CI/CINTB_64b
@@ -34,8 +34,8 @@ helpfunction() {
 	echo ""
 	echo ""
 	echo "Usage: $0 -g [GCC version] -o [Target OS type]"
-	echo -e "\t-g GCC version you want to compile?: (7.1.0|7.2.0|7.3.0|7.4.0|7.5.0|8.1.0|8.2.0|8.3.0|8.4.0|9.1.0|9.2.0|9.3.0|9.4.0|10.1.0|10.2.0|10.3.0)"
-	echo -e "\t-o What's yours Target Raspberry Pi OS type?: (stretch|buster|bullseye)"
+	echo -e "\t-g GCC version you want to compile?: (8.4.0|9.1.0|9.2.0|9.3.0|9.4.0|10.1.0|10.2.0|10.3.0|11.1.0|11.2.0|11.3.0|12.1.0|12.2.0|12.3.0|12.4.0|13.1.0|13.2.0|13.3.0|14.1.0|14.2.0)"
+	echo -e "\t-o What's yours Target Raspberry Pi OS type?: (buster|bullseye|bookworm)"
 	echo ""
 	echo ""
 	exit 1 # Exits script after printing help
@@ -59,23 +59,25 @@ else
 	echo "Parameters configured!"
 fi
 
-# skip bullseye base
-if [ "$RPIOS_TYPE" != "bullseye" ] && [ "$GCC_VERSION" = "10.2.0" ]; then
-	echo "Invalid GCC: $GCC_VERSION!"
-	exit
-fi
-
-if [ "$RPIOS_TYPE" = "buster" ]; then
-	if echo ${GCC_VERSION%.*} "8.3" | awk '{exit ( $1 >= $2 )}'; then
+#collect dependencies versions from raspberry pi os
+if [ "$RPIOS_TYPE" = "bookworm" ]; then
+	if echo ${GCC_VERSION%.*} "12.2" | awk '{exit ( $1 > $2 )}'; then
+		echo "$GCC_VERSION is not supported on bookworm!"
+		exit 0
+	fi
+elif [ "$RPIOS_TYPE" = "buster" ]; then
+	if echo ${GCC_VERSION%.*} "8.3" | awk '{exit ( $1 > $2 )}'; then
 		echo "$GCC_VERSION is not supported on buster!"
 		exit 0
 	fi
-fi
-if [ "$RPIOS_TYPE" = "bullseye" ]; then
-	if echo ${GCC_VERSION%.*} "10.2" | awk '{exit ( $1 >= $2 )}'; then
+elif [ "$RPIOS_TYPE" = "bullseye" ]; then
+	if echo ${GCC_VERSION%.*} "10.2" | awk '{exit ( $1 > $2 )}'; then
 		echo "$GCC_VERSION is not supported on bullseye!"
 		exit 0
 	fi
+else
+	echo "Invalid argument value: $RPIOS_TYPE"
+	exit 1
 fi
 
 #collect build directory if not defined
@@ -96,7 +98,7 @@ fi
 FOLDER_VERSION=64
 ARCH=armv8-a+fp+simd
 TARGET=aarch64-linux-gnu
-GDB_VERSION=10.2
+GDB_VERSION=15.1
 
 #validate env variables
 if [ "$ARCH" != "armv8-a+fp+simd" ]; then exit 1; fi
@@ -117,18 +119,6 @@ else
 	exit 1
 fi
 
-# exit if GCC < 9.0.0 for buster
-if [ "$RPIOS_TYPE" = "buster" ] && [ "$GCC_VERSION" \< "9.0.0" ]; then
-	echo "Invalid GCC for buster: $GCC_VERSION!"
-	exit
-fi
-
-# exit if GCC < 9.0.0 for bullseye
-if [ "$RPIOS_TYPE" = "bullseye" ] && [ "$GCC_VERSION" \< "10.2.0" ]; then
-	echo "Invalid GCC for bullseye: $GCC_VERSION!"
-	exit
-fi
-
 echo "Downloading and Setting up build directories"
 #setup paths
 DOWNLOADDIR=$BUILDDIR/build_toolchains
@@ -141,7 +131,7 @@ if [ ! -f "cross-gcc-$GCC_VERSION-pi_$FOLDER_VERSION.tar.gz" ]; then
 	wget "${URL}cross-gcc-$GCC_VERSION-pi_$FOLDER_VERSION.tar.gz"
 	tar xf cross-gcc-$GCC_VERSION-pi_$FOLDER_VERSION.tar.gz
 	mv cross-pi-gcc-$GCC_VERSION-$FOLDER_VERSION $BUILDDIR
-	rm ./*.tar.*
+	rm ./*.tar.* || true
 fi
 if [ ! -d "gdb-$GDB_VERSION" ]; then
 	if [ ! -f "gdb-$GDB_VERSION.tar.xz" ]; then
@@ -151,7 +141,7 @@ if [ ! -d "gdb-$GDB_VERSION" ]; then
 	cd gdb-$GDB_VERSION || exit
 	mkdir -p build
 	cd "$DOWNLOADDIR" || exit
-	rm ./*.tar.*
+	rm ./*.tar.* || true
 fi
 if [ ! -d "gcc-$GCC_VERSION" ]; then
 	# Download patched GCC 10 series for bullseye
@@ -167,9 +157,9 @@ if [ ! -d "gcc-$GCC_VERSION" ]; then
 	mkdir -p build
 	sed -i contrib/download_prerequisites -e '/base_url=/s/ftp/http/'
 	contrib/download_prerequisites
-	rm ./*.tar.*
+	rm ./*.tar.* || true
 	cd "$DOWNLOADDIR" || exit
-	rm ./*.tar.*
+	rm ./*.tar.* || true
 fi
 
 echo "Setting up paths..."
