Major enhancements and Bug Fixes
- Fixed typos and missing definitions in build-scripts.
- Removed Obsolete Toolchain Binaries.
- Removed redundant 9.1.0 and 8.3.0 builds from toolchains.
- Added new GitHub CI workflow `builder_64.yml` for 64-bit toolchain builds.
- Replaced GZIP with PIGZ as TAR backend for parallel compressed builds.
- Refractored code and replaces `CLI` with `CI`.
- Added new bash utility script `SF_docs_deployer` for auto deploying docs to SourceForge Server
- Added new `docs` directory for storing SourceForge readme doc files.
- Revamped `README.md` with better readability.
- Added necessary updated information to docs.
- Removed redundant information from docs.
- Added new logos and badges.
- Added descriptive and beautiful diagrams.

diff --git a/build-scripts/CI/CIBB_64b b/build-scripts/CI/CIBB_64b
--- a/build-scripts/CI/CIBB_64b
+++ b/build-scripts/CI/CIBB_64b
@@ -26,136 +26,121 @@
 
 
 
-# This script auto downloads, compiles, and compresses Cross & Native GCC ARM Toolchain binaries 
-# targeting Raspberry Pi 32-bit Stretch(Debian 9) and Buster(Debian 10) OSes only.
-
+# This script aauto downloads, compiles, and compresses Cross & Native GCC ARM64 Toolchain 
+# binaries targeting any Raspberry Pi 64-bit (like Pi64) OSes.
 
 
 helpfunction()
 {	
    #helper function that prints custom usage help menu
    echo ""
-   echo "Usage: $0 -g [GCC version] -r [Target Pi type] -o [Target Pi OS type]"
+   echo ""
+   figlet -t -k -f /usr/share/figlet/standard.flf "Raspberry Pi CLI Toolchains Base Builder 64-bit"
+   echo ""
+   figlet -t -k -f /usr/share/figlet/term.flf "Copyright (c) 2020 abhiTronix"
+   echo ""
+   echo ""
+   echo "Usage: $0 -g [GCC version] -t [OS Type]"
    echo -e "\t-g GCC base version?: (6.3.0|8.3.0)"
-   echo -e "\t-r What's yours Raspberry Pi type?: (0-1|2-3|3+)"
-   echo -e "\t-o What's yours Raspberry Pi OS type?: (stretch|buster)"
-   exit 1 # Exit script after printing help
+   echo -e "\t-t What's yours Raspberry Pi OS type?: (1|2) [default:1]"
+   echo ""
+   echo ""
+   exit 1 # Exits script after printing help
 }
 
 
+
 #input arguments handler
-while getopts "g:r:o:" opt
+while getopts "g:t:" opt
 do
    case "$opt" in
    	  g ) GCC_VERSION="$OPTARG" ;;
-      r ) RPI_TYPE="$OPTARG" ;;
-      o ) RPIOS_TYPE="$OPTARG" ;;
+      t ) OS_TYPE="$OPTARG" ;;
       ? ) helpfunction ;; #prints help function for invalid parameter
    esac
 done
 #validates parameters and print usage helper function in case parameters are missing
-if [ -z "$GCC_VERSION" ] || [ -z "$RPI_TYPE" ] || [ -z "$RPIOS_TYPE" ]
-then
-   echo "Required parameters are missing!";
+if [ -z "$GCC_VERSION" ]; then
+   echo "Required parameter is missing!";
    helpfunction
-fi
-
-
-
-#collect parameters from raspbery pi type
-if [ "$RPI_TYPE" = "2-3" ]; then
-	FOLDER_VERSION=1
-	KERNEL=kernel7
-	ARCH=armv7-a
-	FPU=neon-vfpv4;
-elif [ "$RPI_TYPE" = "3+" ]; then
-	FOLDER_VERSION=2
-	KERNEL=kernel7
-	ARCH=armv8-a
-	FPU=neon-fp-armv8
-elif [ "$RPI_TYPE" = "0-1" ]; then
-	FOLDER_VERSION=0
-	KERNEL=kernel
-	ARCH=armv6
-	FPU=vfp
+elif [ -z "$OS_TYPE" ]; then
+	OS_TYPE=1
 else
-	echo "Invalid argument value: $RPI_TYPE"
-	exit
+	echo "Parameters configured!";
 fi
 
 #collect dependencies versions from raspberry pi os
-if [ "$RPIOS_TYPE" = "stretch" ]; then
+if [ "$OS_TYPE" = "1" ]; then
 	GLIBC_VERSION=2.24
 	BINUTILS_VERSION=2.28
-elif [ "$RPIOS_TYPE" = "buster" ]; then
+elif [ "$OS_TYPE" = "2" ]; then
 	GLIBC_VERSION=2.28
 	BINUTILS_VERSION=2.31
 else
-	echo "Invalid argument value: $RPIOS_TYPE"
+	echo "Invalid argument value: $OS_TYPE"
 	exit
 fi
 
+
 #collect build directory if not defined
 if [ "$BUILDDIR" = "" ]; then
-	#select temp directory as default
+	#select temp directory
 	echo "Build directory is empty, using temp directory!"
 	BUILDDIR=$(dirname "$(mktemp tmp.XXXXXXXXXX -ut)")
 fi
 
 #collect programming languages if not defined
 if [ "$LANGUAGES" = "" ]; then
-	#select `c,c++,fortran` as default
+	#select temp directory
 	echo "Building binaries for c,c++,fortran programming languages!"
 	LANGUAGES=c,c++,fortran
 fi
 
+
 #pre-defined params
-TARGET=arm-linux-gnueabihf
+FOLDER_VERSION=64
+KERNEL=kernel7
+ARCH=armv8-a+fp+simd
+TARGET=aarch64-linux-gnu
 GDB_VERSION=8.3.1
+
 
 #validate env variables
 if ! [[ "$GCC_VERSION" =~ ^(6.3.0|8.3.0)$ ]]; then exit 1 ; fi
 if ! [[ "$GLIBC_VERSION" =~ ^(2.24|2.28)$ ]]; then exit 1 ; fi
 if ! [[ "$BINUTILS_VERSION" =~ ^(2.28|2.31)$ ]]; then exit 1 ; fi
-if ! [[ "$FOLDER_VERSION" =~ ^(0|1|2)$ ]]; then exit 1 ; fi
-if ! [[ "$KERNEL" =~ ^(kernel|kernel7)$ ]]; then exit 1 ; fi
-if ! [[ "$ARCH" =~ ^(armv6|armv7-a|armv8-a)$ ]]; then exit 1 ; fi
-if ! [[ "$FPU" =~ ^(vfp|neon-vfpv4|neon-fp-armv8)$ ]]; then exit 1 ; fi
+if [ "$KERNEL" != "kernel7" ]; then exit 1 ; fi
+if [ "$ARCH" != "armv8-a+fp+simd" ]; then exit 1 ; fi
+if [ "$FOLDER_VERSION" != "64" ]; then exit 1 ; fi
 if [ "$BUILDDIR" = "" ]; then exit 1 ; fi
 if [ "$LANGUAGES" = "" ]; then exit 1 ; fi
 
 
-if [ "$CI" != "true" ]; then
-	echo ""
-	echo ""
-	figlet -t -k -f /usr/share/figlet/standard.flf "Raspberry Pi Toolchains Builder"
-	echo ""
-	echo ""
-fi
-
-#download binaries if not found
 echo "Downloading and Setting up build directories"
-
+#setup paths
 DOWNLOADDIR=$BUILDDIR/build_toolchains
 INSTALLDIR=$BUILDDIR/cross-pi-gcc-$GCC_VERSION-$FOLDER_VERSION
 SYSROOTDIR=$BUILDDIR/cross-pi-gcc-$GCC_VERSION-$FOLDER_VERSION/$TARGET/libc
 
+#make dirs
 mkdir -p "$DOWNLOADDIR"
 mkdir -p "$INSTALLDIR"
 
 cd "$DOWNLOADDIR" || exit
-
+#download binaries if not found
 if [ ! -d "linux" ]; then
-	wget -q https://github.com/$(wget -q https://github.com/raspberrypi/linux/releases/latest -O - | grep -E '/.*/.*/.*.tar.gz' -o)
+	wget -q https://github.com/$(wget -q https://github.com/raspberrypi/linux/releases/latest -O - | egrep '/.*/.*/.*.tar.gz' -o)
 	tar xf raspberrypi*.tar.gz
 	mv linux* linux
 	rm ./*.tar.*
 fi
 if [ ! -d "gcc-$GCC_VERSION" ]; then
-	if [ ! -f "gcc-$GCC_VERSION.tar.gz" ]; then wget -q https://ftpmirror.gnu.org/gcc/gcc-$GCC_VERSION/gcc-$GCC_VERSION.tar.gz; fi
+	if [ ! -f "gcc-$GCC_VERSION.tar.gz" ]; then 
+		wget -q https://ftpmirror.gnu.org/gcc/gcc-$GCC_VERSION/gcc-$GCC_VERSION.tar.gz; 
+	fi
 	tar xf gcc-$GCC_VERSION.tar.gz
 	cd gcc-$GCC_VERSION || exit
-	mkdir -p build
+	mkdir -p build 
 	if [ "$GCC_VERSION" = "6.3.0" ]; then
 		sed -i contrib/download_prerequisites -e 's/ftp/http/';
 	else
@@ -168,7 +153,9 @@ if [ ! -d "gcc-$GCC_VERSION" ]; then
 	rm ./*.tar.*
 fi
 if [ ! -d "binutils-$BINUTILS_VERSION" ]; then
-	if [ ! -f "binutils-$BINUTILS_VERSION.tar.bz2" ]; then wget -q https://ftp.gnu.org/gnu/binutils/binutils-$BINUTILS_VERSION.tar.bz2; fi
+	if [ ! -f "binutils-$BINUTILS_VERSION.tar.bz2" ]; then 
+		wget -q https://ftp.gnu.org/gnu/binutils/binutils-$BINUTILS_VERSION.tar.bz2; 
+	fi
 	tar xf binutils-$BINUTILS_VERSION.tar.bz2
 	cd binutils-$BINUTILS_VERSION || exit
 	mkdir -p build 
@@ -176,14 +163,15 @@ if [ ! -d "binutils-$BINUTILS_VERSION" ]; then
 	rm ./*.tar.*
 fi
 if [ ! -d "glibc-$GLIBC_VERSION" ]; then
-	if [ ! -f "glibc-$GLIBC_VERSION.tar.bz2" ]; then wget -q https://ftpmirror.gnu.org/glibc/glibc-$GLIBC_VERSION.tar.bz2; fi
+	if [ ! -f "glibc-$GLIBC_VERSION.tar.bz2" ]; then 
+		wget -q https://ftpmirror.gnu.org/glibc/glibc-$GLIBC_VERSION.tar.bz2; 
+	fi
 	tar xf  glibc-$GLIBC_VERSION.tar.bz2
 	cd glibc-$GLIBC_VERSION || exit
 	mkdir -p build 
 	cd "$DOWNLOADDIR" || exit
 	rm ./*.tar.*
 fi
-
 
 echo "Setting up paths..."
 PATH=$BUILDDIR/cross-pi-gcc-$GCC_VERSION-$FOLDER_VERSION/bin:$PATH
@@ -193,28 +181,28 @@ unset LD_LIBRARY_PATH #patch
 echo "Building Kernel Headers..."
 cd "$DOWNLOADDIR"/linux || exit
 KERNEL=$KERNEL
-make -s ARCH=arm INSTALL_HDR_PATH="$SYSROOTDIR"/usr headers_install
+make -s ARCH=arm64 INSTALL_HDR_PATH="$SYSROOTDIR"/usr headers_install
 mkdir -p "$SYSROOTDIR"/usr/lib
 
 
 echo "Building binutils..."
 if [ -n "$(ls -A "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build/*; fi
 cd "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build || exit
-../configure --target=$TARGET --prefix= --with-arch=$ARCH  --with-fpu=$FPU --with-float=hard --disable-multilib
+../configure --target=$TARGET --prefix= --with-arch=$ARCH  --disable-multilib
 make -s -j$(getconf _NPROCESSORS_ONLN)
 make -s install DESTDIR="$INSTALLDIR"
 if [ -n "$(ls -A "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build/*; fi
 
 
-echo "Building Cross GCC $GCC_VERSION Binaries..."
+echo "Building Cross GCC $GCC_VERSION BASE Binaries..."
 if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-$GCC_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-$GCC_VERSION/build/*; fi
 cd "$DOWNLOADDIR"/gcc-$GCC_VERSION/build || exit
-../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH  --with-fpu=$FPU --with-float=hard --disable-multilib
+../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH  --disable-multilib
 make -s -j$(getconf _NPROCESSORS_ONLN) all-gcc
 make -s install-gcc DESTDIR="$INSTALLDIR"
 if [ -n "$(ls -A "$DOWNLOADDIR"/glibc-$GLIBC_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/glibc-$GLIBC_VERSION/build/*; fi
 cd "$DOWNLOADDIR"/glibc-$GLIBC_VERSION/build || exit
-../configure --prefix=/usr --build="$MACHTYPE" --host=$TARGET --target=$TARGET --with-arch=$ARCH  --with-fpu=$FPU --with-float=hard --with-headers="$SYSROOTDIR"/usr/include --with-lib="$SYSROOTDIR"/usr/lib --disable-multilib libc_cv_forced_unwind=yes
+../configure --prefix=/usr --build="$MACHTYPE" --host=$TARGET --target=$TARGET --with-arch=$ARCH  --with-headers="$SYSROOTDIR"/usr/include --with-lib="$SYSROOTDIR"/usr/lib --disable-multilib libc_cv_forced_unwind=yes
 make -s install-bootstrap-headers=yes install-headers DESTDIR="$SYSROOTDIR"
 make -s -j$(getconf _NPROCESSORS_ONLN) csu/subdir_lib
 install csu/crt1.o csu/crti.o csu/crtn.o "$SYSROOTDIR"/usr/lib
@@ -230,12 +218,13 @@ cd "$DOWNLOADDIR"/gcc-$GCC_VERSION/build || exit
 if [ -n "$(ls -A "$DOWNLOADDIR"/glibc-$GLIBC_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/glibc-$GLIBC_VERSION/build/*; fi
 make -s -j$(getconf _NPROCESSORS_ONLN)
 make -s install DESTDIR="$INSTALLDIR"
+if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-$GCC_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-$GCC_VERSION/build/*; fi
 
 mv "$BUILDDIR"/cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION "$HOME"
 cd "$HOME" || exit
 #compress with maximum possible compression level.
-tar cf - cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 > cross-gcc-"$GCC_VERSION"-pi_"$RPI_TYPE".tar.gz
-echo "Done Building Cross GCC $GCC_VERSION Binaries..."
+tar cf - cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 > cross-gcc-"$GCC_VERSION"-pi_"$FOLDER_VERSION".tar.gz
+echo "Done Building Cross GCC $GCC_VERSION BASE Binaries..."
 
 #clean path
 PATH=$(echo "$PATH" | sed -e 's;:\?$BUILDDIR/cross-pi-gcc-$GCC_VERSION-$FOLDER_VERSION/bin;;' -e 's;$BUILDDIR/cross-pi-gcc-$GCC_VERSION-$FOLDER_VERSION/bin:\?;;')
