Initial support for Raspbian Bullseye OS(Debian 11) ARM/ARM64 Raspberry Pi Toolchains. (Fixes #84)
- Added GCC version `10.2.0` as Bullseye toolchains base.
- Added Binutils version `2.35.2` as Bullseye toolchains base.
- Added GLIBC version `2.31` as Bullseye toolchains base.
- Updated User and CI bash scripts.
- Updated Binary and Docs Sourceforge deployer.
- Updated complete Docs and links.
- Remove obsolete GCC versions from docs.

diff --git a/build-scripts/CI/CIBB_64b b/build-scripts/CI/CIBB_64b
--- a/build-scripts/CI/CIBB_64b
+++ b/build-scripts/CI/CIBB_64b
@@ -35,7 +35,7 @@ helpfunction() {
 	echo ""
 	echo "Usage: $0 -g [GCC version] -o [Target Pi OS type]"
 	echo -e "\t-g GCC base version?: (6.3.0|8.3.0)"
-	echo -e "\t-o What's yours Target Raspberry Pi OS type?: (stretch|buster)"
+	echo -e "\t-o What's yours Target Raspberry Pi OS type?: (stretch|buster|bullseye)"
 	echo ""
 	echo ""
 	exit 1 # Exits script after printing help
@@ -66,6 +66,9 @@ if [ "$RPIOS_TYPE" = "stretch" ]; then
 elif [ "$RPIOS_TYPE" = "buster" ]; then
 	GLIBC_VERSION=2.28
 	BINUTILS_VERSION=2.31.1
+elif [ "$RPIOS_TYPE" = "bullseye" ]; then
+	GLIBC_VERSION=2.31
+	BINUTILS_VERSION=2.35.2
 else
 	echo "Invalid argument value: $RPIOS_TYPE"
 	exit
@@ -78,6 +81,11 @@ fi
 # exit if not valid GCC
 if [ "$RPIOS_TYPE" = "buster" ] && [ "$GCC_VERSION" != "8.3.0" ]; then
 	echo "Invalid GCC for buster: $GCC_VERSION!"
+	exit
+fi
+# exit if not valid GCC
+if [ "$RPIOS_TYPE" = "bullseye" ] && [ "$GCC_VERSION" != "10.2.0" ]; then
+	echo "Invalid GCC for bullseye: $GCC_VERSION!"
 	exit
 fi
 
@@ -103,9 +111,9 @@ TARGET=aarch64-linux-gnu
 GDB_VERSION=10.2
 
 #validate env variables
-if ! [[ "$GCC_VERSION" =~ ^(6.3.0|8.3.0)$ ]]; then exit 1; fi
-if ! [[ "$GLIBC_VERSION" =~ ^(2.24|2.28)$ ]]; then exit 1; fi
-if ! [[ "$BINUTILS_VERSION" =~ ^(2.28|2.31.1)$ ]]; then exit 1; fi
+if ! [[ "$GCC_VERSION" =~ ^(6.3.0|8.3.0|10.2.0)$ ]]; then exit 1; fi
+if ! [[ "$GLIBC_VERSION" =~ ^(2.24|2.28|2.31)$ ]]; then exit 1; fi
+if ! [[ "$BINUTILS_VERSION" =~ ^(2.28|2.31.1|2.35.2)$ ]]; then exit 1; fi
 if [ "$KERNEL" != "kernel8" ]; then exit 1; fi
 if [ "$ARCH" != "armv8-a+fp+simd" ]; then exit 1; fi
 if [ "$FOLDER_VERSION" != "64" ]; then exit 1; fi
diff --git a/build-scripts/CI/CICTB_32b b/build-scripts/CI/CICTB_32b
--- a/build-scripts/CI/CICTB_32b
+++ b/build-scripts/CI/CICTB_32b
@@ -36,7 +36,7 @@ helpfunction() {
 	echo "Usage: $0 -g [GCC version] -r [Target Pi type] -o [Target Pi OS type]"
 	echo -e "\t-g GCC version you want to compile?: (7.1.0|7.2.0|7.3.0|7.4.0|7.5.0|8.1.0|8.2.0|8.3.0|8.4.0|9.1.0|9.2.0|9.3.0|9.4.0|10.1.0|10.2.0|10.3.0)"
 	echo -e "\t-r What's yours Target Raspberry Pi type?: (0-1|2-3|3+)"
-	echo -e "\t-o What's yours Target Raspberry Pi OS type?: (stretch|buster)"
+	echo -e "\t-o What's yours Target Raspberry Pi OS type?: (stretch|buster|bullseye)"
 	echo ""
 	echo ""
 	exit 1 # Exit script after printing help
@@ -90,6 +90,13 @@ elif [ "$RPIOS_TYPE" = "buster" ]; then
 	else
 		GCCBASE_VERSION=8.3.0
 	fi
+elif [ "$RPIOS_TYPE" = "bullseye" ]; then
+	if echo ${GCC_VERSION%.*} "10.2" | awk '{exit ( $1 >= $2 )}'; then
+		echo "$GCC_VERSION is not supported on bullseye!"
+		exit 0
+	else
+		GCCBASE_VERSION=10.2.0
+	fi
 else
 	echo "Invalid argument value: $RPIOS_TYPE"
 	exit 1
@@ -114,7 +121,7 @@ TARGET=arm-linux-gnueabihf
 GDB_VERSION=10.2
 
 #validate env variables
-if ! [[ "$GCCBASE_VERSION" =~ ^(6.3.0|8.3.0)$ ]]; then exit 1; fi
+if ! [[ "$GCCBASE_VERSION" =~ ^(6.3.0|8.3.0|10.2.0)$ ]]; then exit 1; fi
 if ! [[ "$FOLDER_VERSION" =~ ^(0|1|2)$ ]]; then exit 1; fi
 if ! [[ "$ARCH" =~ ^(armv6|armv7-a|armv8-a)$ ]]; then exit 1; fi
 if ! [[ "$FPU" =~ ^(vfp|neon-vfpv4|neon-fp-armv8)$ ]]; then exit 1; fi
@@ -125,6 +132,18 @@ URL="https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/CLI%20B
 
 if [ "$RPIOS_TYPE" = "buster" ]; then
 	URL="$URL/Buster/GCC%20$GCCBASE_VERSION"
+	if [ "$RPI_TYPE" = "0-1" ]; then
+		URL="$URL/Raspberry%20Pi%201%2C%20Zero/"
+	elif [ "$RPI_TYPE" = "2-3" ]; then
+		URL="$URL/Raspberry%20Pi%202%2C%203/"
+	elif [ "$RPI_TYPE" = "3+" ]; then
+		URL="$URL/Raspberry%20Pi%203A%2B%2C%203B%2B%2C%204/"
+	else
+		echo "Missing RPI_TYPE parameter!"
+		exit 1
+	fi
+elif [ "$RPIOS_TYPE" = "bullseye" ]; then
+	URL="$URL/Bullseye/GCC%20$GCCBASE_VERSION"
 	if [ "$RPI_TYPE" = "0-1" ]; then
 		URL="$URL/Raspberry%20Pi%201%2C%20Zero/"
 	elif [ "$RPI_TYPE" = "2-3" ]; then
diff --git a/build-scripts/CI/CINTB_32b b/build-scripts/CI/CINTB_32b
--- a/build-scripts/CI/CINTB_32b
+++ b/build-scripts/CI/CINTB_32b
@@ -36,7 +36,7 @@ helpfunction() {
 	echo "Usage: $0 -g [GCC version] -r [Target Pi type] -o [Target Pi OS type]"
 	echo -e "\t-g GCC version you want to compile?: (7.1.0|7.2.0|7.3.0|7.4.0|7.5.0|8.1.0|8.2.0|8.3.0|8.4.0|9.1.0|9.2.0|9.3.0|9.4.0|10.1.0|10.2.0|10.3.0)"
 	echo -e "\t-r What's yours Target Raspberry Pi type?: (0-1|2-3|3+)"
-	echo -e "\t-o What's yours Target Raspberry Pi OS type?: (stretch|buster)"
+	echo -e "\t-o What's yours Target Raspberry Pi OS type?: (stretch|buster|bullseye)"
 	echo ""
 	echo ""
 	exit 1 # Exit script after printing help
@@ -60,6 +60,13 @@ fi
 if [ "$RPIOS_TYPE" = "buster" ]; then
 	if echo ${GCC_VERSION%.*} "8.3" | awk '{exit ( $1 >= $2 )}'; then
 		echo "$GCC_VERSION is not supported on buster!"
+		exit 0
+	fi
+fi
+
+if [ "$RPIOS_TYPE" = "bullseye" ]; then
+	if echo ${GCC_VERSION%.*} "10.2" | awk '{exit ( $1 >= $2 )}'; then
+		echo "$GCC_VERSION is not supported on bullseye!"
 		exit 0
 	fi
 fi
@@ -111,6 +118,18 @@ URL="https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Raspber
 
 if [ "$RPIOS_TYPE" = "buster" ]; then
 	URL="$URL/Buster/GCC%20$GCC_VERSION"
+	if [ "$RPI_TYPE" = "0-1" ]; then
+		URL="$URL/Raspberry%20Pi%201%2C%20Zero/"
+	elif [ "$RPI_TYPE" = "2-3" ]; then
+		URL="$URL/Raspberry%20Pi%202%2C%203/"
+	elif [ "$RPI_TYPE" = "3+" ]; then
+		URL="$URL/Raspberry%20Pi%203A%2B%2C%203B%2B%2C%204/"
+	else
+		echo "Missing RPI_TYPE parameter!"
+		exit 1
+	fi
+elif [ "$RPIOS_TYPE" = "bullseye" ]; then
+	URL="$URL/Bullseye/GCC%20$GCC_VERSION"
 	if [ "$RPI_TYPE" = "0-1" ]; then
 		URL="$URL/Raspberry%20Pi%201%2C%20Zero/"
 	elif [ "$RPI_TYPE" = "2-3" ]; then
