Enhancement: Sourceforge Docs Handling Redesigned
- New Workflow yaml to specifically handle docs uploads.
- Reformatted SF_docs_deployer util script.
- New docs files.
- Stripped docs uploading for toolchain yamls.
- Properly formatted all bash scripts in the project.

diff --git a/build-scripts/CI/CIBB_32b b/build-scripts/CI/CIBB_32b
--- a/build-scripts/CI/CIBB_32b
+++ b/build-scripts/CI/CIBB_32b
@@ -1,14 +1,11 @@
 #!/bin/bash
 
-
 # ===============================================
-# Raspberry Pi Toolchains(raspberry-pi-cross-compilers): This project 
-# provides latest automated GCC Cross Compiler & Native (ARM & ARM64) 
+# Raspberry Pi Toolchains(raspberry-pi-cross-compilers): This project
+# provides latest automated GCC Cross Compiler & Native (ARM & ARM64)
 # build-scripts and precompiled standalone toolchains for Raspberry Pi.
 
-
 # Copyright (C) 2020 Abhishek Thakur(@abhiTronix) <abhi.una12@gmail.com>
-
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -24,46 +21,38 @@
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 # ===============================================
 
-
-
-# This script auto downloads, compiles, and compresses Cross & Native GCC ARM Toolchain binaries 
+# This script auto downloads, compiles, and compresses Cross & Native GCC ARM Toolchain binaries
 # targeting Raspberry Pi 32-bit Stretch(Debian 9) and Buster(Debian 10) OSes only.
 
-
-
-helpfunction()
-{	
-   #helper function that prints custom usage help menu
-   echo ""
-   echo ""
-   figlet -t -k -f /usr/share/figlet/standard.flf "Raspberry Pi CLI Toolchains Base Builder 32-bit"
-   echo ""
-   figlet -t -k -f /usr/share/figlet/term.flf "Copyright (c) 2020 abhiTronix"
-   echo ""
-   echo ""
-   echo "Usage: $0 -g [GCC version] -r [Target Pi type] -o [Target Pi OS type]"
-   echo -e "\t-r What's yours Raspberry Pi type?: (0-1|2-3|3+)"
-   echo -e "\t-o What's yours Raspberry Pi OS type?: (stretch|buster)"
-   echo ""
-   echo ""
-   exit 1 # Exit script after printing help
+helpfunction() {
+	#helper function that prints custom usage help menu
+	echo ""
+	echo ""
+	figlet -t -k -f /usr/share/figlet/standard.flf "Raspberry Pi CLI Toolchains Base Builder 32-bit"
+	echo ""
+	figlet -t -k -f /usr/share/figlet/term.flf "Copyright (c) 2020 abhiTronix"
+	echo ""
+	echo ""
+	echo "Usage: $0 -g [GCC version] -r [Target Pi type] -o [Target Pi OS type]"
+	echo -e "\t-r What's yours Raspberry Pi type?: (0-1|2-3|3+)"
+	echo -e "\t-o What's yours Raspberry Pi OS type?: (stretch|buster)"
+	echo ""
+	echo ""
+	exit 1 # Exit script after printing help
 }
 
-
 #input arguments handler
-while getopts "r:o:" opt
-do
-   case "$opt" in
-      r ) RPI_TYPE="$OPTARG" ;;
-      o ) RPIOS_TYPE="$OPTARG" ;;
-      ? ) helpfunction ;; #prints help function for invalid parameter
-   esac
+while getopts "r:o:" opt; do
+	case "$opt" in
+	r) RPI_TYPE="$OPTARG" ;;
+	o) RPIOS_TYPE="$OPTARG" ;;
+	?) helpfunction ;; #prints help function for invalid parameter
+	esac
 done
 #validates parameters and print usage helper function in case parameters are missing
-if [ -z "$RPI_TYPE" ] || [ -z "$RPIOS_TYPE" ]
-then
-   echo "Required parameters are missing!";
-   helpfunction
+if [ -z "$RPI_TYPE" ] || [ -z "$RPIOS_TYPE" ]; then
+	echo "Required parameters are missing!"
+	helpfunction
 fi
 
 #collect parameters from raspbery pi type
@@ -71,7 +60,7 @@ if [ "$RPI_TYPE" = "2-3" ]; then
 	FOLDER_VERSION=1
 	KERNEL=kernel7
 	ARCH=armv7-a
-	FPU=neon-vfpv4;
+	FPU=neon-vfpv4
 elif [ "$RPI_TYPE" = "3+" ]; then
 	FOLDER_VERSION=2
 	KERNEL=kernel7
@@ -120,15 +109,15 @@ TARGET=arm-linux-gnueabihf
 GDB_VERSION=9.2
 
 #validate env variables
-if ! [[ "$GCC_VERSION" =~ ^(6.3.0|8.3.0)$ ]]; then exit 1 ; fi
-if ! [[ "$GLIBC_VERSION" =~ ^(2.24|2.28)$ ]]; then exit 1 ; fi
-if ! [[ "$BINUTILS_VERSION" =~ ^(2.28|2.31)$ ]]; then exit 1 ; fi
-if ! [[ "$FOLDER_VERSION" =~ ^(0|1|2)$ ]]; then exit 1 ; fi
-if ! [[ "$KERNEL" =~ ^(kernel|kernel7)$ ]]; then exit 1 ; fi
-if ! [[ "$ARCH" =~ ^(armv6|armv7-a|armv8-a)$ ]]; then exit 1 ; fi
-if ! [[ "$FPU" =~ ^(vfp|neon-vfpv4|neon-fp-armv8)$ ]]; then exit 1 ; fi
-if [ "$BUILDDIR" = "" ]; then exit 1 ; fi
-if [ "$LANGUAGES" = "" ]; then exit 1 ; fi
+if ! [[ "$GCC_VERSION" =~ ^(6.3.0|8.3.0)$ ]]; then exit 1; fi
+if ! [[ "$GLIBC_VERSION" =~ ^(2.24|2.28)$ ]]; then exit 1; fi
+if ! [[ "$BINUTILS_VERSION" =~ ^(2.28|2.31)$ ]]; then exit 1; fi
+if ! [[ "$FOLDER_VERSION" =~ ^(0|1|2)$ ]]; then exit 1; fi
+if ! [[ "$KERNEL" =~ ^(kernel|kernel7)$ ]]; then exit 1; fi
+if ! [[ "$ARCH" =~ ^(armv6|armv7-a|armv8-a)$ ]]; then exit 1; fi
+if ! [[ "$FPU" =~ ^(vfp|neon-vfpv4|neon-fp-armv8)$ ]]; then exit 1; fi
+if [ "$BUILDDIR" = "" ]; then exit 1; fi
+if [ "$LANGUAGES" = "" ]; then exit 1; fi
 
 #download binaries if not found
 echo "Downloading and Setting up build directories"
@@ -154,9 +143,9 @@ if [ ! -d "gcc-$GCC_VERSION" ]; then
 	cd gcc-$GCC_VERSION || exit
 	mkdir -p build
 	if [ "$GCC_VERSION" = "6.3.0" ]; then
-		sed -i contrib/download_prerequisites -e 's/ftp/http/';
+		sed -i contrib/download_prerequisites -e 's/ftp/http/'
 	else
-		sed -i contrib/download_prerequisites -e '/base_url=/s/ftp/http/';
+		sed -i contrib/download_prerequisites -e '/base_url=/s/ftp/http/'
 	fi
 	contrib/download_prerequisites
 	rm ./*.tar.*
@@ -168,24 +157,22 @@ if [ ! -d "binutils-$BINUTILS_VERSION" ]; then
 	if [ ! -f "binutils-$BINUTILS_VERSION.tar.bz2" ]; then wget -q https://ftp.gnu.org/gnu/binutils/binutils-$BINUTILS_VERSION.tar.bz2; fi
 	tar xf binutils-$BINUTILS_VERSION.tar.bz2
 	cd binutils-$BINUTILS_VERSION || exit
-	mkdir -p build 
+	mkdir -p build
 	cd "$DOWNLOADDIR" || exit
 	rm ./*.tar.*
 fi
 if [ ! -d "glibc-$GLIBC_VERSION" ]; then
 	if [ ! -f "glibc-$GLIBC_VERSION.tar.bz2" ]; then wget -q https://ftpmirror.gnu.org/glibc/glibc-$GLIBC_VERSION.tar.bz2; fi
-	tar xf  glibc-$GLIBC_VERSION.tar.bz2
+	tar xf glibc-$GLIBC_VERSION.tar.bz2
 	cd glibc-$GLIBC_VERSION || exit
-	mkdir -p build 
+	mkdir -p build
 	cd "$DOWNLOADDIR" || exit
 	rm ./*.tar.*
 fi
 
-
 echo "Setting up paths..."
 PATH=$BUILDDIR/cross-pi-gcc-$GCC_VERSION-$FOLDER_VERSION/bin:$PATH
 unset LD_LIBRARY_PATH #patch
-
 
 echo "Building Kernel Headers..."
 cd "$DOWNLOADDIR"/linux || exit
@@ -193,25 +180,23 @@ KERNEL=$KERNEL
 make -s ARCH=arm INSTALL_HDR_PATH="$SYSROOTDIR"/usr headers_install
 mkdir -p "$SYSROOTDIR"/usr/lib
 
-
 echo "Building binutils..."
 if [ -n "$(ls -A "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build/*; fi
 cd "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build || exit
-../configure --target=$TARGET --prefix= --with-arch=$ARCH  --with-fpu=$FPU --with-float=hard --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --disable-multilib
+../configure --target=$TARGET --prefix= --with-arch=$ARCH --with-fpu=$FPU --with-float=hard --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --disable-multilib
 make -s -j$(getconf _NPROCESSORS_ONLN)
 make -s install DESTDIR="$INSTALLDIR"
 if [ -n "$(ls -A "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build/*; fi
 
-
 echo "Building Cross GCC $GCC_VERSION BASE Binaries..."
 if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-$GCC_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-$GCC_VERSION/build/*; fi
 cd "$DOWNLOADDIR"/gcc-$GCC_VERSION/build || exit
-../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH  --with-fpu=$FPU --with-float=hard --disable-multilib
+../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH --with-fpu=$FPU --with-float=hard --disable-multilib
 make -s -j$(getconf _NPROCESSORS_ONLN) all-gcc
 make -s install-gcc DESTDIR="$INSTALLDIR"
 if [ -n "$(ls -A "$DOWNLOADDIR"/glibc-$GLIBC_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/glibc-$GLIBC_VERSION/build/*; fi
 cd "$DOWNLOADDIR"/glibc-$GLIBC_VERSION/build || exit
-../configure --prefix=/usr --build="$MACHTYPE" --host=$TARGET --target=$TARGET --with-arch=$ARCH  --with-fpu=$FPU --with-float=hard --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-headers="$SYSROOTDIR"/usr/include --with-lib="$SYSROOTDIR"/usr/lib --disable-multilib libc_cv_forced_unwind=yes
+../configure --prefix=/usr --build="$MACHTYPE" --host=$TARGET --target=$TARGET --with-arch=$ARCH --with-fpu=$FPU --with-float=hard --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-headers="$SYSROOTDIR"/usr/include --with-lib="$SYSROOTDIR"/usr/lib --disable-multilib libc_cv_forced_unwind=yes
 make -s install-bootstrap-headers=yes install-headers DESTDIR="$SYSROOTDIR"
 make -s -j$(getconf _NPROCESSORS_ONLN) csu/subdir_lib
 install csu/crt1.o csu/crti.o csu/crtn.o "$SYSROOTDIR"/usr/lib
@@ -231,7 +216,7 @@ make -s install DESTDIR="$INSTALLDIR"
 mv "$BUILDDIR"/cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION "$HOME"
 cd "$HOME" || exit
 #compress with maximum possible compression level.
-tar cf - cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 > cross-gcc-"$GCC_VERSION"-pi_"$RPI_TYPE".tar.gz
+tar cf - cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 >cross-gcc-"$GCC_VERSION"-pi_"$RPI_TYPE".tar.gz
 echo "Done Building Cross GCC $GCC_VERSION BASE Binaries..."
 
 #clean path
diff --git a/build-scripts/CI/CIBB_64b b/build-scripts/CI/CIBB_64b
--- a/build-scripts/CI/CIBB_64b
+++ b/build-scripts/CI/CIBB_64b
@@ -1,14 +1,11 @@
 #!/bin/bash
 
-
 # ===============================================
-# Raspberry Pi Toolchains(raspberry-pi-cross-compilers): This project 
-# provides latest automated GCC Cross Compiler & Native (ARM & ARM64) 
+# Raspberry Pi Toolchains(raspberry-pi-cross-compilers): This project
+# provides latest automated GCC Cross Compiler & Native (ARM & ARM64)
 # build-scripts and precompiled standalone toolchains for Raspberry Pi.
 
-
 # Copyright (C) 2020 Abhishek Thakur(@abhiTronix) <abhi.una12@gmail.com>
-
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -24,49 +21,42 @@
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 # ===============================================
 
-
-
-# This script aauto downloads, compiles, and compresses Cross & Native GCC ARM64 Toolchain 
+# This script aauto downloads, compiles, and compresses Cross & Native GCC ARM64 Toolchain
 # binaries targeting any Raspberry Pi 64-bit (like Pi64) OSes.
 
-
-helpfunction()
-{	
-   #helper function that prints custom usage help menu
-   echo ""
-   echo ""
-   figlet -t -k -f /usr/share/figlet/standard.flf "Raspberry Pi CLI Toolchains Base Builder 64-bit"
-   echo ""
-   figlet -t -k -f /usr/share/figlet/term.flf "Copyright (c) 2020 abhiTronix"
-   echo ""
-   echo ""
-   echo "Usage: $0 -g [GCC version] -t [OS Type]"
-   echo -e "\t-g GCC base version?: (6.3.0|8.3.0)"
-   echo -e "\t-t What's yours Raspberry Pi OS type?: (1|2) [default:1]"
-   echo ""
-   echo ""
-   exit 1 # Exits script after printing help
+helpfunction() {
+	#helper function that prints custom usage help menu
+	echo ""
+	echo ""
+	figlet -t -k -f /usr/share/figlet/standard.flf "Raspberry Pi CLI Toolchains Base Builder 64-bit"
+	echo ""
+	figlet -t -k -f /usr/share/figlet/term.flf "Copyright (c) 2020 abhiTronix"
+	echo ""
+	echo ""
+	echo "Usage: $0 -g [GCC version] -t [OS Type]"
+	echo -e "\t-g GCC base version?: (6.3.0|8.3.0)"
+	echo -e "\t-t What's yours Raspberry Pi OS type?: (1|2) [default:1]"
+	echo ""
+	echo ""
+	exit 1 # Exits script after printing help
 }
 
-
-
 #input arguments handler
-while getopts "g:t:" opt
-do
-   case "$opt" in
-   	  g ) GCC_VERSION="$OPTARG" ;;
-      t ) OS_TYPE="$OPTARG" ;;
-      ? ) helpfunction ;; #prints help function for invalid parameter
-   esac
+while getopts "g:t:" opt; do
+	case "$opt" in
+	g) GCC_VERSION="$OPTARG" ;;
+	t) OS_TYPE="$OPTARG" ;;
+	?) helpfunction ;; #prints help function for invalid parameter
+	esac
 done
 #validates parameters and print usage helper function in case parameters are missing
 if [ -z "$GCC_VERSION" ]; then
-   echo "Required parameter is missing!";
-   helpfunction
+	echo "Required parameter is missing!"
+	helpfunction
 elif [ -z "$OS_TYPE" ]; then
 	OS_TYPE=1
 else
-	echo "Parameters configured!";
+	echo "Parameters configured!"
 fi
 
 #collect dependencies versions from raspberry pi os
@@ -80,7 +70,6 @@ else
 	echo "Invalid argument value: $OS_TYPE"
 	exit
 fi
-
 
 #collect build directory if not defined
 if [ "$BUILDDIR" = "" ]; then
@@ -96,7 +85,6 @@ if [ "$LANGUAGES" = "" ]; then
 	LANGUAGES=c,c++,fortran
 fi
 
-
 #pre-defined params
 FOLDER_VERSION=64
 KERNEL=kernel7
@@ -104,17 +92,15 @@ ARCH=armv8-a+fp+simd
 TARGET=aarch64-linux-gnu
 GDB_VERSION=9.2
 
-
 #validate env variables
-if ! [[ "$GCC_VERSION" =~ ^(6.3.0|8.3.0)$ ]]; then exit 1 ; fi
-if ! [[ "$GLIBC_VERSION" =~ ^(2.24|2.28)$ ]]; then exit 1 ; fi
-if ! [[ "$BINUTILS_VERSION" =~ ^(2.28|2.31)$ ]]; then exit 1 ; fi
-if [ "$KERNEL" != "kernel7" ]; then exit 1 ; fi
-if [ "$ARCH" != "armv8-a+fp+simd" ]; then exit 1 ; fi
-if [ "$FOLDER_VERSION" != "64" ]; then exit 1 ; fi
-if [ "$BUILDDIR" = "" ]; then exit 1 ; fi
-if [ "$LANGUAGES" = "" ]; then exit 1 ; fi
-
+if ! [[ "$GCC_VERSION" =~ ^(6.3.0|8.3.0)$ ]]; then exit 1; fi
+if ! [[ "$GLIBC_VERSION" =~ ^(2.24|2.28)$ ]]; then exit 1; fi
+if ! [[ "$BINUTILS_VERSION" =~ ^(2.28|2.31)$ ]]; then exit 1; fi
+if [ "$KERNEL" != "kernel7" ]; then exit 1; fi
+if [ "$ARCH" != "armv8-a+fp+simd" ]; then exit 1; fi
+if [ "$FOLDER_VERSION" != "64" ]; then exit 1; fi
+if [ "$BUILDDIR" = "" ]; then exit 1; fi
+if [ "$LANGUAGES" = "" ]; then exit 1; fi
 
 echo "Downloading and Setting up build directories"
 #setup paths
@@ -135,16 +121,16 @@ if [ ! -d "linux" ]; then
 	rm ./*.tar.*
 fi
 if [ ! -d "gcc-$GCC_VERSION" ]; then
-	if [ ! -f "gcc-$GCC_VERSION.tar.gz" ]; then 
-		wget -q https://ftpmirror.gnu.org/gcc/gcc-$GCC_VERSION/gcc-$GCC_VERSION.tar.gz; 
+	if [ ! -f "gcc-$GCC_VERSION.tar.gz" ]; then
+		wget -q https://ftpmirror.gnu.org/gcc/gcc-$GCC_VERSION/gcc-$GCC_VERSION.tar.gz
 	fi
 	tar xf gcc-$GCC_VERSION.tar.gz
 	cd gcc-$GCC_VERSION || exit
-	mkdir -p build 
+	mkdir -p build
 	if [ "$GCC_VERSION" = "6.3.0" ]; then
-		sed -i contrib/download_prerequisites -e 's/ftp/http/';
+		sed -i contrib/download_prerequisites -e 's/ftp/http/'
 	else
-		sed -i contrib/download_prerequisites -e '/base_url=/s/ftp/http/';
+		sed -i contrib/download_prerequisites -e '/base_url=/s/ftp/http/'
 	fi
 	contrib/download_prerequisites
 	rm ./*.tar.*
@@ -153,22 +139,22 @@ if [ ! -d "gcc-$GCC_VERSION" ]; then
 	rm ./*.tar.*
 fi
 if [ ! -d "binutils-$BINUTILS_VERSION" ]; then
-	if [ ! -f "binutils-$BINUTILS_VERSION.tar.bz2" ]; then 
-		wget -q https://ftp.gnu.org/gnu/binutils/binutils-$BINUTILS_VERSION.tar.bz2; 
+	if [ ! -f "binutils-$BINUTILS_VERSION.tar.bz2" ]; then
+		wget -q https://ftp.gnu.org/gnu/binutils/binutils-$BINUTILS_VERSION.tar.bz2
 	fi
 	tar xf binutils-$BINUTILS_VERSION.tar.bz2
 	cd binutils-$BINUTILS_VERSION || exit
-	mkdir -p build 
+	mkdir -p build
 	cd "$DOWNLOADDIR" || exit
 	rm ./*.tar.*
 fi
 if [ ! -d "glibc-$GLIBC_VERSION" ]; then
-	if [ ! -f "glibc-$GLIBC_VERSION.tar.bz2" ]; then 
-		wget -q https://ftpmirror.gnu.org/glibc/glibc-$GLIBC_VERSION.tar.bz2; 
+	if [ ! -f "glibc-$GLIBC_VERSION.tar.bz2" ]; then
+		wget -q https://ftpmirror.gnu.org/glibc/glibc-$GLIBC_VERSION.tar.bz2
 	fi
-	tar xf  glibc-$GLIBC_VERSION.tar.bz2
+	tar xf glibc-$GLIBC_VERSION.tar.bz2
 	cd glibc-$GLIBC_VERSION || exit
-	mkdir -p build 
+	mkdir -p build
 	cd "$DOWNLOADDIR" || exit
 	rm ./*.tar.*
 fi
@@ -177,13 +163,11 @@ echo "Setting up paths..."
 PATH=$BUILDDIR/cross-pi-gcc-$GCC_VERSION-$FOLDER_VERSION/bin:$PATH
 unset LD_LIBRARY_PATH #patch
 
-
 echo "Building Kernel Headers..."
 cd "$DOWNLOADDIR"/linux || exit
 KERNEL=$KERNEL
 make -s ARCH=arm64 INSTALL_HDR_PATH="$SYSROOTDIR"/usr headers_install
 mkdir -p "$SYSROOTDIR"/usr/lib
-
 
 echo "Building binutils..."
 if [ -n "$(ls -A "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build/*; fi
@@ -193,11 +177,10 @@ make -s -j$(getconf _NPROCESSORS_ONLN)
 make -s install DESTDIR="$INSTALLDIR"
 if [ -n "$(ls -A "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build/*; fi
 
-
 echo "Building Cross GCC $GCC_VERSION BASE Binaries..."
 if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-$GCC_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-$GCC_VERSION/build/*; fi
 cd "$DOWNLOADDIR"/gcc-$GCC_VERSION/build || exit
-../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH  --disable-multilib
+../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH --disable-multilib
 make -s -j$(getconf _NPROCESSORS_ONLN) all-gcc
 make -s install-gcc DESTDIR="$INSTALLDIR"
 if [ -n "$(ls -A "$DOWNLOADDIR"/glibc-$GLIBC_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/glibc-$GLIBC_VERSION/build/*; fi
@@ -223,7 +206,7 @@ if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-$GCC_VERSION/build)" ]; then rm -rf "$DOWNLO
 mv "$BUILDDIR"/cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION "$HOME"
 cd "$HOME" || exit
 #compress with maximum possible compression level.
-tar cf - cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 > cross-gcc-"$GCC_VERSION"-pi_"$FOLDER_VERSION".tar.gz
+tar cf - cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 >cross-gcc-"$GCC_VERSION"-pi_"$FOLDER_VERSION".tar.gz
 echo "Done Building Cross GCC $GCC_VERSION BASE Binaries..."
 
 #clean path
diff --git a/build-scripts/CI/CICTB_32b b/build-scripts/CI/CICTB_32b
--- a/build-scripts/CI/CICTB_32b
+++ b/build-scripts/CI/CICTB_32b
@@ -1,14 +1,11 @@
 #!/bin/bash
 
-
 # ===============================================
-# Raspberry Pi Toolchains(raspberry-pi-cross-compilers): This project 
-# provides latest automated GCC Cross Compiler & Native (ARM & ARM64) 
+# Raspberry Pi Toolchains(raspberry-pi-cross-compilers): This project
+# provides latest automated GCC Cross Compiler & Native (ARM & ARM64)
 # build-scripts and precompiled standalone toolchains for Raspberry Pi.
 
-
 # Copyright (C) 2020 Abhishek Thakur(@abhiTronix) <abhi.una12@gmail.com>
-
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -24,58 +21,47 @@
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 # ===============================================
 
-
-
-# This script auto downloads, compiles, and compresses Cross & Native GCC ARM Toolchain binaries 
+# This script auto downloads, compiles, and compresses Cross & Native GCC ARM Toolchain binaries
 # targeting Raspberry Pi 32-bit Stretch(Debian 9) and Buster(Debian 10) OSes only.
 
-
-
-helpfunction()
-{	
-   #helper function that prints custom usage help menu
-   echo ""
-   echo ""
-   figlet -t -k -f /usr/share/figlet/standard.flf "CLI Raspberry Pi Cross Toolchains Builder 32-bit"
-   echo ""
-   figlet -t -k -f /usr/share/figlet/term.flf "Copyright (c) 2020 abhiTronix"
-   echo ""
-   echo ""
-   echo "Usage: $0 -g [GCC version] -r [Target Pi type] -o [Target Pi OS type]"
-   echo -e "\t-g GCC version you want to compile?: (7.1.0|7.2.0|7.3.0|7.4.0|7.5.0|8.1.0|8.2.0|8.3.0|8.4.0|9.1.0|9.2.0|9.3.0|10.1.0|10.2.0)"
-   echo -e "\t-r What's yours Target Raspberry Pi type?: (0-1|2-3|3+)"
-   echo -e "\t-o What's yours Target Raspberry Pi OS type?: (stretch|buster)"
-   echo ""
-   echo ""
-   exit 1 # Exit script after printing help
+helpfunction() {
+	#helper function that prints custom usage help menu
+	echo ""
+	echo ""
+	figlet -t -k -f /usr/share/figlet/standard.flf "CLI Raspberry Pi Cross Toolchains Builder 32-bit"
+	echo ""
+	figlet -t -k -f /usr/share/figlet/term.flf "Copyright (c) 2020 abhiTronix"
+	echo ""
+	echo ""
+	echo "Usage: $0 -g [GCC version] -r [Target Pi type] -o [Target Pi OS type]"
+	echo -e "\t-g GCC version you want to compile?: (7.1.0|7.2.0|7.3.0|7.4.0|7.5.0|8.1.0|8.2.0|8.3.0|8.4.0|9.1.0|9.2.0|9.3.0|10.1.0|10.2.0)"
+	echo -e "\t-r What's yours Target Raspberry Pi type?: (0-1|2-3|3+)"
+	echo -e "\t-o What's yours Target Raspberry Pi OS type?: (stretch|buster)"
+	echo ""
+	echo ""
+	exit 1 # Exit script after printing help
 }
 
-
-
 #input arguments handler
-while getopts "g:r:o:" opt
-do
-   case "$opt" in
-   	  g ) GCC_VERSION="$OPTARG" ;;
-      r ) RPI_TYPE="$OPTARG" ;;
-      o ) RPIOS_TYPE="$OPTARG" ;;
-      ? ) helpfunction ;; #prints help function for invalid parameter
-   esac
+while getopts "g:r:o:" opt; do
+	case "$opt" in
+	g) GCC_VERSION="$OPTARG" ;;
+	r) RPI_TYPE="$OPTARG" ;;
+	o) RPIOS_TYPE="$OPTARG" ;;
+	?) helpfunction ;; #prints help function for invalid parameter
+	esac
 done
 #validates parameters and print usage helper function in case parameters are missing
-if [ -z "$GCC_VERSION" ] || [ -z "$RPI_TYPE" ] || [ -z "$RPIOS_TYPE" ]
-then
-   echo "Error: Required parameters are missing!";
-   helpfunction
+if [ -z "$GCC_VERSION" ] || [ -z "$RPI_TYPE" ] || [ -z "$RPIOS_TYPE" ]; then
+	echo "Error: Required parameters are missing!"
+	helpfunction
 fi
-
-
 
 #collect parameters from raspbery pi type
 if [ "$RPI_TYPE" = "2-3" ]; then
 	FOLDER_VERSION=1
 	ARCH=armv7-a
-	FPU=neon-vfpv4;
+	FPU=neon-vfpv4
 elif [ "$RPI_TYPE" = "3+" ]; then
 	FOLDER_VERSION=2
 	ARCH=armv8-a
@@ -91,7 +77,7 @@ fi
 
 #collect dependencies versions from raspberry pi os
 if [ "$RPIOS_TYPE" = "stretch" ]; then
-	if [ "$GCC_VERSION" == "8.3.0" ];then
+	if [ "$GCC_VERSION" == "8.3.0" ]; then
 		echo "$GCC_VERSION is not supported on stretch!"
 		exit 0
 	else
@@ -99,7 +85,7 @@ if [ "$RPIOS_TYPE" = "stretch" ]; then
 	fi
 elif [ "$RPIOS_TYPE" = "buster" ]; then
 	if echo ${GCC_VERSION%.*} "8.3" | awk '{exit ( $1 >= $2 )}'; then
-        echo "$GCC_VERSION is not supported on buster!"
+		echo "$GCC_VERSION is not supported on buster!"
 		exit 0
 	else
 		GCCBASE_VERSION=8.3.0
@@ -128,13 +114,12 @@ TARGET=arm-linux-gnueabihf
 GDB_VERSION=9.2
 
 #validate env variables
-if ! [[ "$GCCBASE_VERSION" =~ ^(6.3.0|8.3.0)$ ]]; then exit 1 ; fi
-if ! [[ "$FOLDER_VERSION" =~ ^(0|1|2)$ ]]; then exit 1 ; fi
-if ! [[ "$ARCH" =~ ^(armv6|armv7-a|armv8-a)$ ]]; then exit 1 ; fi
-if ! [[ "$FPU" =~ ^(vfp|neon-vfpv4|neon-fp-armv8)$ ]]; then exit 1 ; fi
-if [ "$BUILDDIR" = "" ]; then exit 1 ; fi
-if [ "$LANGUAGES" = "" ]; then exit 1 ; fi
-
+if ! [[ "$GCCBASE_VERSION" =~ ^(6.3.0|8.3.0)$ ]]; then exit 1; fi
+if ! [[ "$FOLDER_VERSION" =~ ^(0|1|2)$ ]]; then exit 1; fi
+if ! [[ "$ARCH" =~ ^(armv6|armv7-a|armv8-a)$ ]]; then exit 1; fi
+if ! [[ "$FPU" =~ ^(vfp|neon-vfpv4|neon-fp-armv8)$ ]]; then exit 1; fi
+if [ "$BUILDDIR" = "" ]; then exit 1; fi
+if [ "$LANGUAGES" = "" ]; then exit 1; fi
 
 URL="https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/CLI%20Base"
 
@@ -148,7 +133,7 @@ if [ "$RPIOS_TYPE" = "buster" ]; then
 		URL="$URL/Raspberry%20Pi%203A%2B%2C%203B%2B%2C%204/"
 	else
 		echo "Missing RPI_TYPE parameter!"
-		exit 1;
+		exit 1
 	fi
 elif [ "$RPIOS_TYPE" = "stretch" ]; then
 	URL="$URL/Stretch/GCC%20$GCCBASE_VERSION"
@@ -160,13 +145,12 @@ elif [ "$RPIOS_TYPE" = "stretch" ]; then
 		URL="$URL/Raspberry%20Pi%203A%2B%2C%203B%2B%2C%204/"
 	else
 		echo "Missing RPI_TYPE parameter!"
-		exit 1;
+		exit 1
 	fi
-else 
+else
 	echo "Missing RPIOS_TYPE parameter!"
-	exit 1;
+	exit 1
 fi
-
 
 #download binaries if not found
 echo "Downloading and Setting up build directories"
@@ -180,7 +164,7 @@ mkdir -p "$INSTALLDIR"
 
 cd "$DOWNLOADDIR" || exit
 
-if [ ! -f "cross-gcc-$GCCBASE_VERSION-pi_$RPI_TYPE.tar.gz" ]; then 
+if [ ! -f "cross-gcc-$GCCBASE_VERSION-pi_$RPI_TYPE.tar.gz" ]; then
 	wget -q "${URL}cross-gcc-$GCCBASE_VERSION-pi_$RPI_TYPE.tar.gz"
 	tar xf cross-gcc-$GCCBASE_VERSION-pi_$RPI_TYPE.tar.gz
 	mv -v cross-pi-gcc-$GCCBASE_VERSION-$FOLDER_VERSION/* $INSTALLDIR
@@ -189,9 +173,9 @@ if [ ! -f "cross-gcc-$GCCBASE_VERSION-pi_$RPI_TYPE.tar.gz" ]; then
 fi
 if [ ! -d "gdb-$GDB_VERSION" ]; then
 	if [ ! -f "gdb-$GDB_VERSION.tar.xz" ]; then wget -q https://ftp.gnu.org/gnu/gdb/gdb-$GDB_VERSION.tar.xz; fi
-	tar xf  gdb-$GDB_VERSION.tar.xz
+	tar xf gdb-$GDB_VERSION.tar.xz
 	cd gdb-$GDB_VERSION || exit
-	mkdir -p build 
+	mkdir -p build
 	cd "$DOWNLOADDIR" || exit
 	rm ./*.tar.*
 fi
@@ -207,7 +191,6 @@ if [ ! -d "gcc-$GCC_VERSION" ]; then
 	rm ./*.tar.*
 fi
 
-
 echo "Setting up paths..."
 PATH=$BUILDDIR/cross-pi-gcc-$GCC_VERSION-$FOLDER_VERSION/bin:$PATH
 unset LD_LIBRARY_PATH #patch
@@ -215,18 +198,18 @@ unset LD_LIBRARY_PATH #patch
 if [ "$GCC_VERSION" != "$GCCBASE_VERSION" ]; then
 	cd "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build || exit
 	if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build/*; fi
-	../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH  --with-fpu=$FPU --with-float=hard  --disable-multilib
+	../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH --with-fpu=$FPU --with-float=hard --disable-multilib
 	make -s -j$(nproc)
 	make -s install DESTDIR="$INSTALLDIR"
 fi
 
-cd  "$DOWNLOADDIR"/gcc-"$GCC_VERSION" || exit
-cat gcc/limitx.h gcc/glimits.h gcc/limity.h > $(dirname $($TARGET-gcc -print-libgcc-file-name))/include-fixed/limits.h
+cd "$DOWNLOADDIR"/gcc-"$GCC_VERSION" || exit
+cat gcc/limitx.h gcc/glimits.h gcc/limity.h >$(dirname $($TARGET-gcc -print-libgcc-file-name))/include-fixed/limits.h
 
 echo "Building Cross GDB Binaries..."
 cd "$DOWNLOADDIR"/gdb-$GDB_VERSION/build || exit
 if [ -n "$(ls -A "$DOWNLOADDIR"/gdb-$GDB_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gdb-$GDB_VERSION/build/*; fi #cleanup
-../configure --prefix= --target=$TARGET --with-arch=$ARCH  --with-fpu=$FPU --with-float=hard -with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR"
+../configure --prefix= --target=$TARGET --with-arch=$ARCH --with-fpu=$FPU --with-float=hard -with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR"
 make -s -j$(nproc)
 make -s install DESTDIR="$INSTALLDIR"
 if [ -n "$(ls -A "$DOWNLOADDIR"/gdb-$GDB_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gdb-$GDB_VERSION/build/*; fi #cleanup
@@ -235,7 +218,7 @@ echo "Done Building Cross GDB Binaries..."
 mv "$BUILDDIR"/cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION "$HOME"
 cd "$HOME" || exit
 #compress with maximum possible compression level.
-tar cf - cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 > cross-gcc-"$GCC_VERSION"-pi_"$RPI_TYPE".tar.gz 
+tar cf - cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 >cross-gcc-"$GCC_VERSION"-pi_"$RPI_TYPE".tar.gz
 echo "Done Building Cross GCC $GCC_VERSION Binaries..."
 rm -rf "$HOME"/cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION
 
diff --git a/build-scripts/CI/x86_64TB b/build-scripts/CI/x86_64TB
--- a/build-scripts/CI/x86_64TB
+++ b/build-scripts/CI/x86_64TB
@@ -1,14 +1,11 @@
 #!/bin/bash
 
-
 # ===============================================
-# Raspberry Pi Toolchains(raspberry-pi-cross-compilers): This project 
-# provides latest automated GCC Desktop Compiler & (ARM & ARM64) 
+# Raspberry Pi Toolchains(raspberry-pi-cross-compilers): This project
+# provides latest automated GCC Desktop Compiler & (ARM & ARM64)
 # build-scripts and precompiled standalone toolchains for Raspberry Pi.
 
-
 # Copyright (C) 2020 Abhishek Thakur(@abhiTronix) <abhi.una12@gmail.com>
-
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -24,49 +21,43 @@
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 # ===============================================
 
-
-
-# This script aauto downloads, compiles, and compresses Desktop & GCC ARM64 Toolchain 
+# This script aauto downloads, compiles, and compresses Desktop & GCC ARM64 Toolchain
 # binaries targeting any Raspberry Pi 64-bit (like Pi64) OSes.
 
-
-helpfunction()
-{	
-   #helper function that prints custom usage help menu
-   echo ""
-   echo ""
-   figlet -t -k -f /usr/share/figlet/standard.flf "CLI Raspberry Pi x86_64 Toolchains Builder"
-   echo ""
-   figlet -t -k -f /usr/share/figlet/term.flf "Copyright (c) 2020 abhiTronix"
-   echo ""
-   echo ""
-   echo "Usage: $0 -g [GCC version] -t [Target OS type]"
-   echo -e "\t-g GCC version you want to compile?: (8.3.0|9.1.0|9.2.0|9.3.0|10.1.0|10.2.0)"
-   echo -e "\t-t What's yours Target OS type?: (x86|x86_64) [default:x86_64]"
-   echo ""
-   echo ""
-   exit 1 # Exits script after printing help
+helpfunction() {
+	#helper function that prints custom usage help menu
+	echo ""
+	echo ""
+	figlet -t -k -f /usr/share/figlet/standard.flf "CLI Raspberry Pi x86_64 Toolchains Builder"
+	echo ""
+	figlet -t -k -f /usr/share/figlet/term.flf "Copyright (c) 2020 abhiTronix"
+	echo ""
+	echo ""
+	echo "Usage: $0 -g [GCC version] -t [Target OS type]"
+	echo -e "\t-g GCC version you want to compile?: (8.3.0|9.1.0|9.2.0|9.3.0|10.1.0|10.2.0)"
+	echo -e "\t-t What's yours Target OS type?: (x86|x86_64) [default:x86_64]"
+	echo ""
+	echo ""
+	exit 1 # Exits script after printing help
 }
 
 #input arguments handler
-while getopts "g:t:" opt
-do
-   case "$opt" in
-   	  g ) GCC_VERSION="$OPTARG" ;;
-      t ) OS_TYPE="$OPTARG" ;;
-      ? ) helpfunction ;; #prints help function for invalid parameter
-   esac
+while getopts "g:t:" opt; do
+	case "$opt" in
+	g) GCC_VERSION="$OPTARG" ;;
+	t) OS_TYPE="$OPTARG" ;;
+	?) helpfunction ;; #prints help function for invalid parameter
+	esac
 done
 #validates parameters and print usage helper function in case parameters are missing
 if [ -z "$GCC_VERSION" ]; then
-   echo "Error: Required parameter is missing!";
-   helpfunction
+	echo "Error: Required parameter is missing!"
+	helpfunction
 elif [ -z "$OS_TYPE" ]; then
 	OS_TYPE=x86_64
 else
-	echo "Parameters configured!";
+	echo "Parameters configured!"
 fi
-
 
 #collect build directory if not defined
 if [ "$BUILDDIR" = "" ]; then
@@ -82,7 +73,7 @@ if [ "$LANGUAGES" = "" ]; then
 	LANGUAGES=c,c++,fortran
 fi
 
-if ! [[ "$OS_TYPE" =~ ^("x86"|"x86_64")$ ]]; then exit 1 ; fi
+if ! [[ "$OS_TYPE" =~ ^("x86"|"x86_64")$ ]]; then exit 1; fi
 
 if [ "$OS_TYPE" = "x86_64" ]; then
 	ARCH_LINUX=x86_64
@@ -95,7 +86,7 @@ else
 fi
 
 if echo ${GCC_VERSION%.*} "8.3" | awk '{exit ( $1 >= $2 )}'; then
-    echo "$GCC_VERSION is not supported!"
+	echo "$GCC_VERSION is not supported!"
 	exit 0
 fi
 
@@ -105,8 +96,8 @@ FOLDER_VERSION=$OS_TYPE
 GDB_VERSION=9.2
 
 #validate env variables
-if [ "$BUILDDIR" = "" ]; then exit 1 ; fi
-if [ "$LANGUAGES" = "" ]; then exit 1 ; fi
+if [ "$BUILDDIR" = "" ]; then exit 1; fi
+if [ "$LANGUAGES" = "" ]; then exit 1; fi
 
 echo "Downloading and Setting up build directories"
 #setup paths
@@ -117,16 +108,16 @@ mkdir -p "$DOWNLOADDIR"
 
 cd "$DOWNLOADDIR" || exit
 if [ ! -d "gcc-$GCC_VERSION" ]; then
-	if [ ! -f "gcc-$GCC_VERSION.tar.gz" ]; then 
-		wget -q https://ftpmirror.gnu.org/gcc/gcc-$GCC_VERSION/gcc-$GCC_VERSION.tar.gz; 
+	if [ ! -f "gcc-$GCC_VERSION.tar.gz" ]; then
+		wget -q https://ftpmirror.gnu.org/gcc/gcc-$GCC_VERSION/gcc-$GCC_VERSION.tar.gz
 	fi
 	tar xf gcc-$GCC_VERSION.tar.gz
 	cd gcc-$GCC_VERSION || exit
-	mkdir -p build 
+	mkdir -p build
 	if [ "$GCC_VERSION" = "6.3.0" ]; then
-		sed -i contrib/download_prerequisites -e 's/ftp/http/';
+		sed -i contrib/download_prerequisites -e 's/ftp/http/'
 	else
-		sed -i contrib/download_prerequisites -e '/base_url=/s/ftp/http/';
+		sed -i contrib/download_prerequisites -e '/base_url=/s/ftp/http/'
 	fi
 	contrib/download_prerequisites
 	rm ./*.tar.*
@@ -135,12 +126,12 @@ if [ ! -d "gcc-$GCC_VERSION" ]; then
 	rm ./*.tar.*
 fi
 if [ ! -d "gdb-$GDB_VERSION" ]; then
-	if [ ! -f "gdb-$GDB_VERSION.tar.xz" ]; then 
-		wget -q https://ftp.gnu.org/gnu/gdb/gdb-$GDB_VERSION.tar.xz; 
+	if [ ! -f "gdb-$GDB_VERSION.tar.xz" ]; then
+		wget -q https://ftp.gnu.org/gnu/gdb/gdb-$GDB_VERSION.tar.xz
 	fi
-	tar xf  gdb-$GDB_VERSION.tar.xz
+	tar xf gdb-$GDB_VERSION.tar.xz
 	cd gdb-$GDB_VERSION || exit
-	mkdir -p build 
+	mkdir -p build
 	cd "$DOWNLOADDIR" || exit
 	rm ./*.tar.*
 fi
@@ -154,12 +145,12 @@ make -s -j$(nproc)
 make -s install-strip DESTDIR="$BUILDDIR"/pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION
 if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build/*; fi
 cd "$DOWNLOADDIR"/gcc-"$GCC_VERSION" || exit
-cat gcc/limitx.h gcc/glimits.h gcc/limity.h > "$BUILDDIR"/pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION/lib/gcc/$TARGET/"$GCC_VERSION"/include-fixed/limits.h
+cat gcc/limitx.h gcc/glimits.h gcc/limity.h >"$BUILDDIR"/pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION/lib/gcc/$TARGET/"$GCC_VERSION"/include-fixed/limits.h
 
 echo "Building Desktop GDB Binaries..."
 cd "$DOWNLOADDIR"/gdb-$GDB_VERSION/build || exit
 if [ -n "$(ls -A "$DOWNLOADDIR"/gdb-$GDB_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gdb-$GDB_VERSION/build/*; fi
-../configure CFLAGS="$C_FLAGS"  CXXFLAGS="$C_FLAGS" --prefix= --build="$MACHTYPE" --host="$MACHTYPE" --target=$TARGET --with-arch=$ARCH  --program-suffix=-"$GCC_VERSION"
+../configure CFLAGS="$C_FLAGS" CXXFLAGS="$C_FLAGS" --prefix= --build="$MACHTYPE" --host="$MACHTYPE" --target=$TARGET --with-arch=$ARCH --program-suffix=-"$GCC_VERSION"
 make -s -j$(nproc)
 make -s install DESTDIR="$BUILDDIR"/pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION
 if [ -n "$(ls -A "$DOWNLOADDIR"/gdb-$GDB_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gdb-$GDB_VERSION/build/*; fi
@@ -168,5 +159,5 @@ echo "Done Building Desktop GDB Binaries..."
 mv "$BUILDDIR"/pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION "$HOME"
 cd "$HOME" || exit
 #compress with maximum possible compression level.
-tar cf - pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 > desktop-gcc-"$GCC_VERSION"-pi_"$OS_TYPE".tar.gz
+tar cf - pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 >desktop-gcc-"$GCC_VERSION"-pi_"$OS_TYPE".tar.gz
 echo "Done Building Desktop GCC $GCC_VERSION Binaries..."
diff --git a/build-scripts/RTBuilder_32b b/build-scripts/RTBuilder_32b
--- a/build-scripts/RTBuilder_32b
+++ b/build-scripts/RTBuilder_32b
@@ -1,14 +1,11 @@
 #!/bin/bash
 
-
 # ===============================================
-# Raspberry Pi Toolchains(raspberry-pi-cross-compilers): This project 
-# provides latest automated GCC Cross Compiler & Native (ARM & ARM64) 
+# Raspberry Pi Toolchains(raspberry-pi-cross-compilers): This project
+# provides latest automated GCC Cross Compiler & Native (ARM & ARM64)
 # build-scripts and precompiled standalone toolchains for Raspberry Pi.
 
-
 # Copyright (C) 2020 Abhishek Thakur(@abhiTronix) <abhi.una12@gmail.com>
-
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -24,59 +21,48 @@
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 # ===============================================
 
-
-
-# This script auto downloads, compiles, and compresses Cross & Native GCC ARM Toolchain binaries 
+# This script auto downloads, compiles, and compresses Cross & Native GCC ARM Toolchain binaries
 # targeting Raspberry Pi 32-bit Stretch(Debian 9) and Buster(Debian 10) OSes only.
 
-
-
-helpfunction()
-{	
-   #helper function that prints custom usage help menu
-   echo ""
-   echo ""
-   figlet -t -k -f /usr/share/figlet/standard.flf "Raspberry Pi Toolchains Builder 32-bit"
-   echo ""
-   figlet -t -k -f /usr/share/figlet/term.flf "Copyright (c) 2020 abhiTronix"
-   echo ""
-   echo ""
-   echo "Usage: $0 -g [GCC version] -r [Target Pi type] -o [Target Pi OS type]"
-   echo -e "\t-g GCC version you want to compile?: (7.1.0|7.2.0|7.3.0|7.4.0|7.5.0|8.1.0|8.2.0|8.3.0|9.1.0|9.2.0|9.3.0|10.1.0|10.2.0)"
-   echo -e "\t-r What's yours Target Raspberry Pi type?: (0-1|2-3|3+)"
-   echo -e "\t-o What's yours Target Raspberry Pi OS type?: (stretch|buster)"
-   echo ""
-   echo ""
-   exit 1 # Exit script after printing help
+helpfunction() {
+	#helper function that prints custom usage help menu
+	echo ""
+	echo ""
+	figlet -t -k -f /usr/share/figlet/standard.flf "Raspberry Pi Toolchains Builder 32-bit"
+	echo ""
+	figlet -t -k -f /usr/share/figlet/term.flf "Copyright (c) 2020 abhiTronix"
+	echo ""
+	echo ""
+	echo "Usage: $0 -g [GCC version] -r [Target Pi type] -o [Target Pi OS type]"
+	echo -e "\t-g GCC version you want to compile?: (7.1.0|7.2.0|7.3.0|7.4.0|7.5.0|8.1.0|8.2.0|8.3.0|9.1.0|9.2.0|9.3.0|10.1.0|10.2.0)"
+	echo -e "\t-r What's yours Target Raspberry Pi type?: (0-1|2-3|3+)"
+	echo -e "\t-o What's yours Target Raspberry Pi OS type?: (stretch|buster)"
+	echo ""
+	echo ""
+	exit 1 # Exit script after printing help
 }
 
-
-
 #input arguments handler
-while getopts "g:r:o:" opt
-do
-   case "$opt" in
-   	  g ) GCC_VERSION="$OPTARG" ;;
-      r ) RPI_TYPE="$OPTARG" ;;
-      o ) RPIOS_TYPE="$OPTARG" ;;
-      ? ) helpfunction ;; #prints help function for invalid parameter
-   esac
+while getopts "g:r:o:" opt; do
+	case "$opt" in
+	g) GCC_VERSION="$OPTARG" ;;
+	r) RPI_TYPE="$OPTARG" ;;
+	o) RPIOS_TYPE="$OPTARG" ;;
+	?) helpfunction ;; #prints help function for invalid parameter
+	esac
 done
 #validates parameters and print usage helper function in case parameters are missing
-if [ -z "$GCC_VERSION" ] || [ -z "$RPI_TYPE" ] || [ -z "$RPIOS_TYPE" ]
-then
-   echo "Error: Required parameters are missing!";
-   helpfunction
+if [ -z "$GCC_VERSION" ] || [ -z "$RPI_TYPE" ] || [ -z "$RPIOS_TYPE" ]; then
+	echo "Error: Required parameters are missing!"
+	helpfunction
 fi
-
-
 
 #collect parameters from raspbery pi type
 if [ "$RPI_TYPE" = "2-3" ]; then
 	FOLDER_VERSION=1
 	KERNEL=kernel7
 	ARCH=armv7-a
-	FPU=neon-vfpv4;
+	FPU=neon-vfpv4
 elif [ "$RPI_TYPE" = "3+" ]; then
 	FOLDER_VERSION=2
 	KERNEL=kernel7
@@ -95,7 +81,7 @@ fi
 #collect dependencies versions from raspberry pi os
 if [ "$RPIOS_TYPE" = "stretch" ]; then
 	if echo ${GCC_VERSION%.*} "6.3" | awk '{exit ( $1 >= $2 )}'; then
-        echo "$GCC_VERSION is not supported on stretch!"
+		echo "$GCC_VERSION is not supported on stretch!"
 		exit 0
 	else
 		GCCBASE_VERSION=6.3.0
@@ -104,7 +90,7 @@ if [ "$RPIOS_TYPE" = "stretch" ]; then
 	BINUTILS_VERSION=2.28
 elif [ "$RPIOS_TYPE" = "buster" ]; then
 	if echo ${GCC_VERSION%.*} "8.3" | awk '{exit ( $1 >= $2 )}'; then
-        echo "$GCC_VERSION is not supported on buster!"
+		echo "$GCC_VERSION is not supported on buster!"
 		exit 0
 	else
 		GCCBASE_VERSION=8.3.0
@@ -135,17 +121,16 @@ TARGET=arm-linux-gnueabihf
 GDB_VERSION=9.2
 
 #validate env variables
-if ! [[ "$GCC_VERSION" =~ ^(7.1.0|7.2.0|7.3.0|7.4.0|7.5.0|8.1.0|8.2.0|8.3.0|9.1.0|9.2.0|9.3.0|10.1.0|10.2.0)$ ]]; then exit 1 ; fi
-if ! [[ "$GCCBASE_VERSION" =~ ^(6.3.0|8.3.0)$ ]]; then exit 1 ; fi
-if ! [[ "$GLIBC_VERSION" =~ ^(2.24|2.28)$ ]]; then exit 1 ; fi
-if ! [[ "$BINUTILS_VERSION" =~ ^(2.28|2.31)$ ]]; then exit 1 ; fi
-if ! [[ "$FOLDER_VERSION" =~ ^(0|1|2)$ ]]; then exit 1 ; fi
-if ! [[ "$KERNEL" =~ ^(kernel|kernel7)$ ]]; then exit 1 ; fi
-if ! [[ "$ARCH" =~ ^(armv6|armv7-a|armv8-a)$ ]]; then exit 1 ; fi
-if ! [[ "$FPU" =~ ^(vfp|neon-vfpv4|neon-fp-armv8)$ ]]; then exit 1 ; fi
-if [ "$BUILDDIR" = "" ]; then exit 1 ; fi
-if [ "$LANGUAGES" = "" ]; then exit 1 ; fi
-
+if ! [[ "$GCC_VERSION" =~ ^(7.1.0|7.2.0|7.3.0|7.4.0|7.5.0|8.1.0|8.2.0|8.3.0|9.1.0|9.2.0|9.3.0|10.1.0|10.2.0)$ ]]; then exit 1; fi
+if ! [[ "$GCCBASE_VERSION" =~ ^(6.3.0|8.3.0)$ ]]; then exit 1; fi
+if ! [[ "$GLIBC_VERSION" =~ ^(2.24|2.28)$ ]]; then exit 1; fi
+if ! [[ "$BINUTILS_VERSION" =~ ^(2.28|2.31)$ ]]; then exit 1; fi
+if ! [[ "$FOLDER_VERSION" =~ ^(0|1|2)$ ]]; then exit 1; fi
+if ! [[ "$KERNEL" =~ ^(kernel|kernel7)$ ]]; then exit 1; fi
+if ! [[ "$ARCH" =~ ^(armv6|armv7-a|armv8-a)$ ]]; then exit 1; fi
+if ! [[ "$FPU" =~ ^(vfp|neon-vfpv4|neon-fp-armv8)$ ]]; then exit 1; fi
+if [ "$BUILDDIR" = "" ]; then exit 1; fi
+if [ "$LANGUAGES" = "" ]; then exit 1; fi
 
 #download binaries if not found
 echo "Downloading and Setting up build directories"
@@ -171,9 +156,9 @@ if [ ! -d "gcc-$GCCBASE_VERSION" ]; then
 	cd gcc-$GCCBASE_VERSION || exit
 	mkdir -p build
 	if [ "$GCCBASE_VERSION" = "6.3.0" ]; then
-		sed -i contrib/download_prerequisites -e 's/ftp/http/';
+		sed -i contrib/download_prerequisites -e 's/ftp/http/'
 	else
-		sed -i contrib/download_prerequisites -e '/base_url=/s/ftp/http/';
+		sed -i contrib/download_prerequisites -e '/base_url=/s/ftp/http/'
 	fi
 	contrib/download_prerequisites
 	rm ./*.tar.*
@@ -185,23 +170,23 @@ if [ ! -d "binutils-$BINUTILS_VERSION" ]; then
 	if [ ! -f "binutils-$BINUTILS_VERSION.tar.bz2" ]; then wget -q https://ftp.gnu.org/gnu/binutils/binutils-$BINUTILS_VERSION.tar.bz2; fi
 	tar xf binutils-$BINUTILS_VERSION.tar.bz2
 	cd binutils-$BINUTILS_VERSION || exit
-	mkdir -p build 
+	mkdir -p build
 	cd "$DOWNLOADDIR" || exit
 	rm ./*.tar.*
 fi
 if [ ! -d "glibc-$GLIBC_VERSION" ]; then
 	if [ ! -f "glibc-$GLIBC_VERSION.tar.bz2" ]; then wget -q https://ftpmirror.gnu.org/glibc/glibc-$GLIBC_VERSION.tar.bz2; fi
-	tar xf  glibc-$GLIBC_VERSION.tar.bz2
+	tar xf glibc-$GLIBC_VERSION.tar.bz2
 	cd glibc-$GLIBC_VERSION || exit
-	mkdir -p build 
+	mkdir -p build
 	cd "$DOWNLOADDIR" || exit
 	rm ./*.tar.*
 fi
 if [ ! -d "gdb-$GDB_VERSION" ]; then
 	if [ ! -f "gdb-$GDB_VERSION.tar.xz" ]; then wget -q https://ftp.gnu.org/gnu/gdb/gdb-$GDB_VERSION.tar.xz; fi
-	tar xf  gdb-$GDB_VERSION.tar.xz
+	tar xf gdb-$GDB_VERSION.tar.xz
 	cd gdb-$GDB_VERSION || exit
-	mkdir -p build 
+	mkdir -p build
 	cd "$DOWNLOADDIR" || exit
 	rm ./*.tar.*
 fi
@@ -217,12 +202,9 @@ if [ ! -d "gcc-$GCC_VERSION" ]; then
 	rm ./*.tar.*
 fi
 
-
-
 echo "Setting up paths..."
 PATH=$BUILDDIR/cross-pi-gcc-$GCC_VERSION-$FOLDER_VERSION/bin:$PATH
 unset LD_LIBRARY_PATH #patch
-
 
 echo "Building Kernel Headers..."
 cd "$DOWNLOADDIR"/linux || exit
@@ -230,25 +212,23 @@ KERNEL=$KERNEL
 make -s ARCH=arm INSTALL_HDR_PATH="$SYSROOTDIR"/usr headers_install
 mkdir -p "$SYSROOTDIR"/usr/lib
 
-
 echo "Building binutils..."
 if [ -n "$(ls -A "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build/*; fi
 cd "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build || exit
-../configure --target=$TARGET --prefix= --with-arch=$ARCH  --with-fpu=$FPU --with-float=hard --disable-multilib
+../configure --target=$TARGET --prefix= --with-arch=$ARCH --with-fpu=$FPU --with-float=hard --disable-multilib
 make -s -j$(nproc)
 make -s install DESTDIR="$INSTALLDIR"
 if [ -n "$(ls -A "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build/*; fi
 
-
 echo "Building Cross GCC $GCCBASE_VERSION Binaries..."
 if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-$GCCBASE_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-$GCCBASE_VERSION/build/*; fi
 cd "$DOWNLOADDIR"/gcc-$GCCBASE_VERSION/build || exit
-../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH  --with-fpu=$FPU --with-float=hard --disable-multilib
+../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH --with-fpu=$FPU --with-float=hard --disable-multilib
 make -s -j$(nproc) all-gcc
 make -s install-gcc DESTDIR="$INSTALLDIR"
 if [ -n "$(ls -A "$DOWNLOADDIR"/glibc-$GLIBC_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/glibc-$GLIBC_VERSION/build/*; fi
 cd "$DOWNLOADDIR"/glibc-$GLIBC_VERSION/build || exit
-../configure --prefix=/usr --build="$MACHTYPE" --host=$TARGET --target=$TARGET --with-arch=$ARCH  --with-fpu=$FPU --with-float=hard --with-headers="$SYSROOTDIR"/usr/include --with-lib="$SYSROOTDIR"/usr/lib --disable-multilib libc_cv_forced_unwind=yes
+../configure --prefix=/usr --build="$MACHTYPE" --host=$TARGET --target=$TARGET --with-arch=$ARCH --with-fpu=$FPU --with-float=hard --with-headers="$SYSROOTDIR"/usr/include --with-lib="$SYSROOTDIR"/usr/lib --disable-multilib libc_cv_forced_unwind=yes
 make -s install-bootstrap-headers=yes install-headers DESTDIR="$SYSROOTDIR"
 make -s -j$(nproc) csu/subdir_lib
 install csu/crt1.o csu/crti.o csu/crtn.o "$SYSROOTDIR"/usr/lib
@@ -269,7 +249,7 @@ if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-$GCCBASE_VERSION/build)" ]; then rm -rf "$DO
 if [ "$GCC_VERSION" != "$GCCBASE_VERSION" ]; then
 	cd "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build || exit
 	if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build/*; fi
-	../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH  --with-fpu=$FPU --with-float=hard  --disable-multilib
+	../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH --with-fpu=$FPU --with-float=hard --disable-multilib
 	make -s -j$(nproc)
 	make -s install DESTDIR="$INSTALLDIR"
 	if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build/*; fi
@@ -278,17 +258,17 @@ if [ "$GCC_VERSION" != "$GCCBASE_VERSION" ]; then
 	mkdir -p "$BUILDDIR"/native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION
 	cd "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build || exit
 	if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build/*; fi
-	../configure --prefix= --build="$MACHTYPE" --host=$TARGET --target=$TARGET --enable-languages=$LANGUAGES --with-arch=$ARCH   --with-fpu=$FPU  --with-float=hard --disable-multilib --program-suffix=-"$GCC_VERSION"
+	../configure --prefix= --build="$MACHTYPE" --host=$TARGET --target=$TARGET --enable-languages=$LANGUAGES --with-arch=$ARCH --with-fpu=$FPU --with-float=hard --disable-multilib --program-suffix=-"$GCC_VERSION"
 	make -s -j$(nproc)
 	make -s install-strip DESTDIR="$BUILDDIR"/native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION
 	if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build/*; fi
 	cd "$DOWNLOADDIR"/gcc-"$GCC_VERSION" || exit
-	cat gcc/limitx.h gcc/glimits.h gcc/limity.h > "$BUILDDIR"/native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION/lib/gcc/$TARGET/"$GCC_VERSION"/include-fixed/limits.h
+	cat gcc/limitx.h gcc/glimits.h gcc/limity.h >"$BUILDDIR"/native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION/lib/gcc/$TARGET/"$GCC_VERSION"/include-fixed/limits.h
 
 	echo "Building Native GDB Binaries..."
 	cd "$DOWNLOADDIR"/gdb-$GDB_VERSION/build || exit
 	if [ -n "$(ls -A "$DOWNLOADDIR"/gdb-$GDB_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gdb-$GDB_VERSION/build/*; fi
-	../configure --prefix= --build="$MACHTYPE" --host=$TARGET --target=$TARGET --with-arch=$ARCH --with-fpu=$FPU --with-float=hard  --program-suffix=-"$GCC_VERSION"
+	../configure --prefix= --build="$MACHTYPE" --host=$TARGET --target=$TARGET --with-arch=$ARCH --with-fpu=$FPU --with-float=hard --program-suffix=-"$GCC_VERSION"
 	make -s -j$(nproc)
 	make -s install DESTDIR="$BUILDDIR"/native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION
 	if [ -n "$(ls -A "$DOWNLOADDIR"/gdb-$GDB_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gdb-$GDB_VERSION/build/*; fi
@@ -297,18 +277,18 @@ if [ "$GCC_VERSION" != "$GCCBASE_VERSION" ]; then
 	mv "$BUILDDIR"/native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION "$HOME"
 	cd "$HOME" || exit
 	#compress with maximum possible compression level.
-	tar cf - native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 > native-gcc-"$GCC_VERSION"-pi_"$RPI_TYPE".tar.gz
+	tar cf - native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 >native-gcc-"$GCC_VERSION"-pi_"$RPI_TYPE".tar.gz
 	rm -rf "$HOME"/native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION
 	echo "Done Building Native GCC $GCC_VERSION Binaries..."
 fi
 
-cd  "$DOWNLOADDIR"/gcc-"$GCC_VERSION" || exit
-cat gcc/limitx.h gcc/glimits.h gcc/limity.h > $(dirname $($TARGET-gcc -print-libgcc-file-name))/include-fixed/limits.h
+cd "$DOWNLOADDIR"/gcc-"$GCC_VERSION" || exit
+cat gcc/limitx.h gcc/glimits.h gcc/limity.h >$(dirname $($TARGET-gcc -print-libgcc-file-name))/include-fixed/limits.h
 
 echo "Building Cross GDB Binaries..."
 cd "$DOWNLOADDIR"/gdb-$GDB_VERSION/build || exit
 if [ -n "$(ls -A "$DOWNLOADDIR"/gdb-$GDB_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gdb-$GDB_VERSION/build/*; fi #cleanup
-../configure --prefix= --target=$TARGET --with-arch=$ARCH  --with-fpu=$FPU --with-float=hard
+../configure --prefix= --target=$TARGET --with-arch=$ARCH --with-fpu=$FPU --with-float=hard
 make -s -j$(nproc)
 make -s install DESTDIR="$INSTALLDIR"
 if [ -n "$(ls -A "$DOWNLOADDIR"/gdb-$GDB_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gdb-$GDB_VERSION/build/*; fi #cleanup
@@ -317,7 +297,7 @@ echo "Done Building Cross GDB Binaries..."
 mv "$BUILDDIR"/cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION "$HOME"
 cd "$HOME" || exit
 #compress with maximum possible compression level.
-tar cf - cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 > cross-gcc-"$GCC_VERSION"-pi_"$RPI_TYPE".tar.gz 
+tar cf - cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 >cross-gcc-"$GCC_VERSION"-pi_"$RPI_TYPE".tar.gz
 echo "Done Building Cross GCC $GCC_VERSION Binaries..."
 rm -rf "$HOME"/cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION
 
diff --git a/build-scripts/RTBuilder_64b b/build-scripts/RTBuilder_64b
--- a/build-scripts/RTBuilder_64b
+++ b/build-scripts/RTBuilder_64b
@@ -1,14 +1,11 @@
 #!/bin/bash
 
-
 # ===============================================
-# Raspberry Pi Toolchains(raspberry-pi-cross-compilers): This project 
-# provides latest automated GCC Cross Compiler & Native (ARM & ARM64) 
+# Raspberry Pi Toolchains(raspberry-pi-cross-compilers): This project
+# provides latest automated GCC Cross Compiler & Native (ARM & ARM64)
 # build-scripts and precompiled standalone toolchains for Raspberry Pi.
 
-
 # Copyright (C) 2020 Abhishek Thakur(@abhiTronix) <abhi.una12@gmail.com>
-
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -24,51 +21,43 @@
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 # ===============================================
 
-
-
-# This script aauto downloads, compiles, and compresses Cross & Native GCC ARM64 Toolchain 
+# This script aauto downloads, compiles, and compresses Cross & Native GCC ARM64 Toolchain
 # binaries targeting any Raspberry Pi 64-bit (like Pi64) OSes.
 
-
-helpfunction()
-{	
-   #helper function that prints custom usage help menu
-   echo ""
-   echo ""
-   figlet -t -k -f /usr/share/figlet/standard.flf "Raspberry Pi Toolchains Builder 64-bit"
-   echo ""
-   figlet -t -k -f /usr/share/figlet/term.flf "Copyright (c) 2020 abhiTronix"
-   echo ""
-   echo ""
-   echo "Usage: $0 -g [GCC version] -t [Target OS type]"
-   echo -e "\t-g GCC version you want to compile?: (7.1.0|7.2.0|7.3.0|7.4.0|7.5.0|8.1.0|8.2.0|8.3.0|9.1.0|9.2.0|9.3.0|10.1.0|10.2.0)"
-   echo -e "\t-t What's yours Target OS type?: (1|2) [default:1]"
-   echo ""
-   echo ""
-   exit 1 # Exits script after printing help
+helpfunction() {
+	#helper function that prints custom usage help menu
+	echo ""
+	echo ""
+	figlet -t -k -f /usr/share/figlet/standard.flf "Raspberry Pi Toolchains Builder 64-bit"
+	echo ""
+	figlet -t -k -f /usr/share/figlet/term.flf "Copyright (c) 2020 abhiTronix"
+	echo ""
+	echo ""
+	echo "Usage: $0 -g [GCC version] -t [Target OS type]"
+	echo -e "\t-g GCC version you want to compile?: (7.1.0|7.2.0|7.3.0|7.4.0|7.5.0|8.1.0|8.2.0|8.3.0|9.1.0|9.2.0|9.3.0|10.1.0|10.2.0)"
+	echo -e "\t-t What's yours Target OS type?: (1|2) [default:1]"
+	echo ""
+	echo ""
+	exit 1 # Exits script after printing help
 }
 
-
-
 #input arguments handler
-while getopts "g:t:" opt
-do
-   case "$opt" in
-   	  g ) GCC_VERSION="$OPTARG" ;;
-      t ) OS_TYPE="$OPTARG" ;;
-      ? ) helpfunction ;; #prints help function for invalid parameter
-   esac
+while getopts "g:t:" opt; do
+	case "$opt" in
+	g) GCC_VERSION="$OPTARG" ;;
+	t) OS_TYPE="$OPTARG" ;;
+	?) helpfunction ;; #prints help function for invalid parameter
+	esac
 done
 #validates parameters and print usage helper function in case parameters are missing
 if [ -z "$GCC_VERSION" ]; then
-   echo "Error: Required parameter is missing!";
-   helpfunction
+	echo "Error: Required parameter is missing!"
+	helpfunction
 elif [ -z "$OS_TYPE" ]; then
 	OS_TYPE=1
 else
-	echo "Parameters configured!";
+	echo "Parameters configured!"
 fi
-
 
 #collect dependencies versions from raspberry pi os
 if [ "$OS_TYPE" = "1" ] || echo ${GCC_VERSION%.*} "8.3" | awk '{exit ( $1 >= $2 )}'; then
@@ -84,7 +73,6 @@ else
 	exit
 fi
 
-
 #collect build directory if not defined
 if [ "$BUILDDIR" = "" ]; then
 	#select temp directory
@@ -99,7 +87,6 @@ if [ "$LANGUAGES" = "" ]; then
 	LANGUAGES=c,c++,fortran
 fi
 
-
 #pre-defined params
 FOLDER_VERSION=64
 KERNEL=kernel7
@@ -107,18 +94,16 @@ ARCH=armv8-a+fp+simd
 TARGET=aarch64-linux-gnu
 GDB_VERSION=9.2
 
-
 #validate env variables
-if ! [[ "$GCC_VERSION" =~ ^(7.1.0|7.2.0|7.3.0|7.4.0|7.5.0|8.1.0|8.2.0|8.3.0|9.1.0|9.2.0|9.3.0|10.1.0|10.2.0)$ ]]; then exit 1 ; fi
-if ! [[ "$GCCBASE_VERSION" =~ ^(6.3.0|8.3.0)$ ]]; then exit 1 ; fi
-if ! [[ "$GLIBC_VERSION" =~ ^(2.24|2.28)$ ]]; then exit 1 ; fi
-if ! [[ "$BINUTILS_VERSION" =~ ^(2.28|2.31)$ ]]; then exit 1 ; fi
-if [ "$KERNEL" != "kernel7" ]; then exit 1 ; fi
-if [ "$ARCH" != "armv8-a+fp+simd" ]; then exit 1 ; fi
-if [ "$FOLDER_VERSION" != "64" ]; then exit 1 ; fi
-if [ "$BUILDDIR" = "" ]; then exit 1 ; fi
-if [ "$LANGUAGES" = "" ]; then exit 1 ; fi
-
+if ! [[ "$GCC_VERSION" =~ ^(7.1.0|7.2.0|7.3.0|7.4.0|7.5.0|8.1.0|8.2.0|8.3.0|9.1.0|9.2.0|9.3.0|10.1.0|10.2.0)$ ]]; then exit 1; fi
+if ! [[ "$GCCBASE_VERSION" =~ ^(6.3.0|8.3.0)$ ]]; then exit 1; fi
+if ! [[ "$GLIBC_VERSION" =~ ^(2.24|2.28)$ ]]; then exit 1; fi
+if ! [[ "$BINUTILS_VERSION" =~ ^(2.28|2.31)$ ]]; then exit 1; fi
+if [ "$KERNEL" != "kernel7" ]; then exit 1; fi
+if [ "$ARCH" != "armv8-a+fp+simd" ]; then exit 1; fi
+if [ "$FOLDER_VERSION" != "64" ]; then exit 1; fi
+if [ "$BUILDDIR" = "" ]; then exit 1; fi
+if [ "$LANGUAGES" = "" ]; then exit 1; fi
 
 echo "Downloading and Setting up build directories"
 #setup paths
@@ -139,16 +124,16 @@ if [ ! -d "linux" ]; then
 	rm ./*.tar.*
 fi
 if [ ! -d "gcc-$GCCBASE_VERSION" ]; then
-	if [ ! -f "gcc-$GCCBASE_VERSION.tar.gz" ]; then 
-		wget -q https://ftpmirror.gnu.org/gcc/gcc-$GCCBASE_VERSION/gcc-$GCCBASE_VERSION.tar.gz; 
+	if [ ! -f "gcc-$GCCBASE_VERSION.tar.gz" ]; then
+		wget -q https://ftpmirror.gnu.org/gcc/gcc-$GCCBASE_VERSION/gcc-$GCCBASE_VERSION.tar.gz
 	fi
 	tar xf gcc-$GCCBASE_VERSION.tar.gz
 	cd gcc-$GCCBASE_VERSION || exit
-	mkdir -p build 
+	mkdir -p build
 	if [ "$GCCBASE_VERSION" = "6.3.0" ]; then
-		sed -i contrib/download_prerequisites -e 's/ftp/http/';
+		sed -i contrib/download_prerequisites -e 's/ftp/http/'
 	else
-		sed -i contrib/download_prerequisites -e '/base_url=/s/ftp/http/';
+		sed -i contrib/download_prerequisites -e '/base_url=/s/ftp/http/'
 	fi
 	contrib/download_prerequisites
 	rm ./*.tar.*
@@ -157,42 +142,42 @@ if [ ! -d "gcc-$GCCBASE_VERSION" ]; then
 	rm ./*.tar.*
 fi
 if [ ! -d "binutils-$BINUTILS_VERSION" ]; then
-	if [ ! -f "binutils-$BINUTILS_VERSION.tar.bz2" ]; then 
-		wget -q https://ftp.gnu.org/gnu/binutils/binutils-$BINUTILS_VERSION.tar.bz2; 
+	if [ ! -f "binutils-$BINUTILS_VERSION.tar.bz2" ]; then
+		wget -q https://ftp.gnu.org/gnu/binutils/binutils-$BINUTILS_VERSION.tar.bz2
 	fi
 	tar xf binutils-$BINUTILS_VERSION.tar.bz2
 	cd binutils-$BINUTILS_VERSION || exit
-	mkdir -p build 
+	mkdir -p build
 	cd "$DOWNLOADDIR" || exit
 	rm ./*.tar.*
 fi
 if [ ! -d "glibc-$GLIBC_VERSION" ]; then
-	if [ ! -f "glibc-$GLIBC_VERSION.tar.bz2" ]; then 
-		wget -q https://ftpmirror.gnu.org/glibc/glibc-$GLIBC_VERSION.tar.bz2; 
+	if [ ! -f "glibc-$GLIBC_VERSION.tar.bz2" ]; then
+		wget -q https://ftpmirror.gnu.org/glibc/glibc-$GLIBC_VERSION.tar.bz2
 	fi
-	tar xf  glibc-$GLIBC_VERSION.tar.bz2
+	tar xf glibc-$GLIBC_VERSION.tar.bz2
 	cd glibc-$GLIBC_VERSION || exit
-	mkdir -p build 
+	mkdir -p build
 	cd "$DOWNLOADDIR" || exit
 	rm ./*.tar.*
 fi
 if [ ! -d "gdb-$GDB_VERSION" ]; then
-	if [ ! -f "gdb-$GDB_VERSION.tar.xz" ]; then 
-		wget -q https://ftp.gnu.org/gnu/gdb/gdb-$GDB_VERSION.tar.xz; 
+	if [ ! -f "gdb-$GDB_VERSION.tar.xz" ]; then
+		wget -q https://ftp.gnu.org/gnu/gdb/gdb-$GDB_VERSION.tar.xz
 	fi
-	tar xf  gdb-$GDB_VERSION.tar.xz
+	tar xf gdb-$GDB_VERSION.tar.xz
 	cd gdb-$GDB_VERSION || exit
-	mkdir -p build 
+	mkdir -p build
 	cd "$DOWNLOADDIR" || exit
 	rm ./*.tar.*
 fi
 if [ ! -d "gcc-$GCC_VERSION" ]; then
-	if [ ! -f "gcc-$GCC_VERSION.tar.gz" ]; then 
-		wget -q  https://ftpmirror.gnu.org/gcc/gcc-"$GCC_VERSION"/gcc-"$GCC_VERSION".tar.gz; 
+	if [ ! -f "gcc-$GCC_VERSION.tar.gz" ]; then
+		wget -q https://ftpmirror.gnu.org/gcc/gcc-"$GCC_VERSION"/gcc-"$GCC_VERSION".tar.gz
 	fi
 	tar xf gcc-"$GCC_VERSION".tar.gz
 	cd gcc-"$GCC_VERSION" || exit
-	mkdir -p build 
+	mkdir -p build
 	sed -i contrib/download_prerequisites -e '/base_url=/s/ftp/http/'
 	contrib/download_prerequisites
 	rm ./*.tar.*
@@ -200,12 +185,9 @@ if [ ! -d "gcc-$GCC_VERSION" ]; then
 	rm ./*.tar.*
 fi
 
-
-
 echo "Setting up paths..."
 PATH=$BUILDDIR/cross-pi-gcc-$GCC_VERSION-$FOLDER_VERSION/bin:$PATH
 unset LD_LIBRARY_PATH #patch
-
 
 echo "Building Kernel Headers..."
 cd "$DOWNLOADDIR"/linux || exit
@@ -213,25 +195,23 @@ KERNEL=$KERNEL
 make -s ARCH=arm64 INSTALL_HDR_PATH="$SYSROOTDIR"/usr headers_install
 mkdir -p "$SYSROOTDIR"/usr/lib
 
-
 echo "Building binutils..."
 if [ -n "$(ls -A "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build/*; fi
 cd "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build || exit
-../configure --target=$TARGET --prefix= --with-arch=$ARCH  --disable-multilib
+../configure --target=$TARGET --prefix= --with-arch=$ARCH --disable-multilib
 make -s -j$(nproc)
 make -s install DESTDIR="$INSTALLDIR"
 if [ -n "$(ls -A "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/binutils-$BINUTILS_VERSION/build/*; fi
 
-
 echo "Building Cross GCC $GCCBASE_VERSION Binaries..."
 if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-$GCCBASE_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-$GCCBASE_VERSION/build/*; fi
 cd "$DOWNLOADDIR"/gcc-$GCCBASE_VERSION/build || exit
-../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH  --disable-multilib
+../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH --disable-multilib
 make -s -j$(nproc) all-gcc
 make -s install-gcc DESTDIR="$INSTALLDIR"
 if [ -n "$(ls -A "$DOWNLOADDIR"/glibc-$GLIBC_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/glibc-$GLIBC_VERSION/build/*; fi
 cd "$DOWNLOADDIR"/glibc-$GLIBC_VERSION/build || exit
-../configure --prefix=/usr --build="$MACHTYPE" --host=$TARGET --target=$TARGET --with-arch=$ARCH  --with-headers="$SYSROOTDIR"/usr/include --with-lib="$SYSROOTDIR"/usr/lib --disable-multilib libc_cv_forced_unwind=yes
+../configure --prefix=/usr --build="$MACHTYPE" --host=$TARGET --target=$TARGET --with-arch=$ARCH --with-headers="$SYSROOTDIR"/usr/include --with-lib="$SYSROOTDIR"/usr/lib --disable-multilib libc_cv_forced_unwind=yes
 make -s install-bootstrap-headers=yes install-headers DESTDIR="$SYSROOTDIR"
 make -s -j$(nproc) csu/subdir_lib
 install csu/crt1.o csu/crti.o csu/crtn.o "$SYSROOTDIR"/usr/lib
@@ -252,7 +232,7 @@ if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-$GCCBASE_VERSION/build)" ]; then rm -rf "$DO
 if [ "$GCC_VERSION" != "$GCCBASE_VERSION" ]; then
 	cd "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build || exit
 	if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build/*; fi
-	../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH   --disable-multilib
+	../configure --prefix= --target=$TARGET --enable-languages=$LANGUAGES --with-sysroot=/$TARGET/libc --with-build-sysroot="$SYSROOTDIR" --with-arch=$ARCH --disable-multilib
 	make -s -j$(nproc)
 	make -s install DESTDIR="$INSTALLDIR"
 	if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build/*; fi
@@ -261,17 +241,17 @@ if [ "$GCC_VERSION" != "$GCCBASE_VERSION" ]; then
 	mkdir -p "$BUILDDIR"/native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION
 	cd "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build || exit
 	if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build/*; fi
-	../configure --prefix= --build="$MACHTYPE" --host=$TARGET --target=$TARGET --enable-languages=$LANGUAGES --with-arch=$ARCH    --disable-multilib --program-suffix=-"$GCC_VERSION"
+	../configure --prefix= --build="$MACHTYPE" --host=$TARGET --target=$TARGET --enable-languages=$LANGUAGES --with-arch=$ARCH --disable-multilib --program-suffix=-"$GCC_VERSION"
 	make -s -j$(nproc)
 	make -s install-strip DESTDIR="$BUILDDIR"/native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION
 	if [ -n "$(ls -A "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build)" ]; then rm -rf "$DOWNLOADDIR"/gcc-"$GCC_VERSION"/build/*; fi
 	cd "$DOWNLOADDIR"/gcc-"$GCC_VERSION" || exit
-	cat gcc/limitx.h gcc/glimits.h gcc/limity.h > "$BUILDDIR"/native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION/lib/gcc/$TARGET/"$GCC_VERSION"/include-fixed/limits.h
+	cat gcc/limitx.h gcc/glimits.h gcc/limity.h >"$BUILDDIR"/native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION/lib/gcc/$TARGET/"$GCC_VERSION"/include-fixed/limits.h
 
 	echo "Building Native GDB Binaries..."
 	cd "$DOWNLOADDIR"/gdb-$GDB_VERSION/build || exit
 	if [ -n "$(ls -A "$DOWNLOADDIR"/gdb-$GDB_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gdb-$GDB_VERSION/build/*; fi
-	../configure --prefix= --build="$MACHTYPE" --host=$TARGET --target=$TARGET --with-arch=$ARCH  --program-suffix=-"$GCC_VERSION"
+	../configure --prefix= --build="$MACHTYPE" --host=$TARGET --target=$TARGET --with-arch=$ARCH --program-suffix=-"$GCC_VERSION"
 	make -s -j$(nproc)
 	make -s install DESTDIR="$BUILDDIR"/native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION
 	if [ -n "$(ls -A "$DOWNLOADDIR"/gdb-$GDB_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gdb-$GDB_VERSION/build/*; fi
@@ -280,18 +260,18 @@ if [ "$GCC_VERSION" != "$GCCBASE_VERSION" ]; then
 	mv "$BUILDDIR"/native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION "$HOME"
 	cd "$HOME" || exit
 	#compress with maximum possible compression level.
-	tar cf - native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 > native-gcc-"$GCC_VERSION"-pi_"$RPI_TYPE".tar.gz
+	tar cf - native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 >native-gcc-"$GCC_VERSION"-pi_"$RPI_TYPE".tar.gz
 	rm -rf "$HOME"/native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION
 	echo "Done Building Native GCC $GCC_VERSION Binaries..."
 fi
 
-cd  "$DOWNLOADDIR"/gcc-"$GCC_VERSION" || exit
-cat gcc/limitx.h gcc/glimits.h gcc/limity.h > $(dirname $($TARGET-gcc -print-libgcc-file-name))/include-fixed/limits.h
+cd "$DOWNLOADDIR"/gcc-"$GCC_VERSION" || exit
+cat gcc/limitx.h gcc/glimits.h gcc/limity.h >$(dirname $($TARGET-gcc -print-libgcc-file-name))/include-fixed/limits.h
 
 echo "Building Cross GDB Binaries..."
 cd "$DOWNLOADDIR"/gdb-$GDB_VERSION/build || exit
 if [ -n "$(ls -A "$DOWNLOADDIR"/gdb-$GDB_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gdb-$GDB_VERSION/build/*; fi
-../configure --prefix= --target=$TARGET --with-arch=$ARCH  --with-float=hard
+../configure --prefix= --target=$TARGET --with-arch=$ARCH --with-float=hard
 make -s -j$(nproc)
 make -s install DESTDIR="$INSTALLDIR"
 if [ -n "$(ls -A "$DOWNLOADDIR"/gdb-$GDB_VERSION/build)" ]; then rm -rf "$DOWNLOADDIR"/gdb-$GDB_VERSION/build/*; fi
@@ -300,7 +280,7 @@ echo "Done Building Cross GDB Binaries..."
 mv "$BUILDDIR"/cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION "$HOME"
 cd "$HOME" || exit
 #compress with maximum possible compression level.
-tar cf - cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 > cross-gcc-"$GCC_VERSION"-pi_"$RPI_TYPE".tar.gz 
+tar cf - cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 >cross-gcc-"$GCC_VERSION"-pi_"$RPI_TYPE".tar.gz
 echo "Done Building Cross GCC $GCC_VERSION Binaries..."
 rm -rf "$HOME"/cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION
 
diff --git a/utils/SF_docs_deployer b/utils/SF_docs_deployer
--- a/utils/SF_docs_deployer
+++ b/utils/SF_docs_deployer
@@ -1,13 +1,11 @@
 #!/bin/bash
 
 # ===============================================
-# Raspberry Pi Toolchains(raspberry-pi-cross-compilers): This project 
-# provides latest automated GCC Cross Compiler & Native (ARM & ARM64) 
+# Raspberry Pi Toolchains(raspberry-pi-cross-compilers): This project
+# provides latest automated GCC Cross Compiler & Native (ARM & ARM64)
 # build-scripts and precompiled standalone toolchains for Raspberry Pi.
 
-
 # Copyright (C) 2020 Abhishek Thakur(@abhiTronix) <abhi.una12@gmail.com>
-
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -23,78 +21,136 @@
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 # ===============================================
 
-
 # This script auto-deploys Toolchain specific README.md to Sourceforge secured server
 
+helpfunction() {
+    #helper function that prints custom usage help menu
+    echo ""
+    echo ""
+    figlet -t -k -f /usr/share/figlet/standard.flf "Raspberry Pi Toolchains Docs Deployer"
+    echo ""
+    figlet -t -k -f /usr/share/figlet/term.flf "Copyright (c) 2020 abhiTronix"
+    echo ""
+    echo ""
+    echo "Usage: $0 -t [Toolchain Type] -f [Folder type] -o [Target Pi OS type] -r [Raspberry Pi type] "
+    echo -e "\t-t Toolchain Type?: (cross|native|cross_64|native_64|CLI)"
+    echo -e "\t-f Upload Folder type?: (root|main|base|experimental)"
+    echo -e "\t-o Raspberry Pi OS type?: (stretch|buster)"
+    echo -e "\t-r What's yours Target Raspberry Pi type?: (0-1|2-3|3+|x86|x86_64)"
+    echo ""
+    echo ""
+    exit 1 # Exit script after printing help
+}
+
+#input arguments handler
+while getopts "t:f:o:r:" opt; do
+    case "$opt" in
+    t) TOOLCHAIN="$OPTARG" ;;
+    f) FOLDER_TYPE="$OPTARG" ;;
+    o) RPIOS_TYPE="$OPTARG" ;;
+    r) RPI_TYPE="$OPTARG" ;;
+    ?) helpfunction ;; #prints help function for invalid parameter
+    esac
+done
+
+#validates parameters and print usage helper function in case parameters are missing
+if [ -z "$TOOLCHAIN" ]; then
+    TOOLCHAIN="others"
+fi
+
+if [ -z "$FOLDER_TYPE" ]; then
+    echo "Error: Required parameters are missing!"
+    helpfunction
+fi
+
+if ! [[ "$FOLDER_TYPE" =~ ^("root"|"main"|"base"|"experimental")$ ]]; then
+    echo "Error: Wrong folder!"
+    exit 1
+fi
 
 # deploy root folder docs
-if [ -f "$HOME/README.md" ] && [ "$BASE" = "true" ]; then
-    FOLDER="CLI Base"
-    curl -k  "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/README.md" --ftp-create-dirs
+if [ "$FOLDER_TYPE" = "root" ]; then
+    if [ -f "$HOME/root/README.md" ]; then
+        curl -k "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/root/README.md" --ftp-create-dirs
+    else
+        echo "Error: No valid Root docs found!"
+        exit 1
+    fi
     exit 0
 fi
 
-if [ -f "$HOME/root/README.md" ]; then
-    if [ "$RPI_TYPE" = "64" ]; then
+if [ "$FOLDER_TYPE" = "base" ] && [ -f "$HOME/base/README.md" ]; then
+    if [[ "$TOOLCHAIN" =~ ^("cross_64"|"native_64")$ ]]; then
         FOLDER="Bonus Raspberry Pi GCC 64-Bit Toolchains"
-        curl -k  "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/root/README.md" --ftp-create-dirs
-    elif [[ "$OS_TYPE" =~ ^("x86"|"x86_64")$ ]]; then
-        FOLDER="Exclusive-Experimental Toolchains/Desktop"
-        curl -k  "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/root/README.md" --ftp-create-dirs
+        curl -k "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/base/README.md" --ftp-create-dirs
     else
-        if [ "$COMPILER_TYPE" = "CROSS" ]; then
+        if [ "$TOOLCHAIN" = "cross" ]; then
             FOLDER="Raspberry Pi GCC Cross-Compiler Toolchains"
-            curl -k  "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/root/README.md" --ftp-create-dirs
-        elif [ "$COMPILER_TYPE" = "NATIVE" ]; then
+            curl -k "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/base/README.md" --ftp-create-dirs
+        elif [ "$TOOLCHAIN" = "native" ]; then
             FOLDER="Raspberry Pi GCC Native-Compiler Toolchains"
-            curl -k  "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/root/README.md" --ftp-create-dirs
+            curl -k "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/base/README.md" --ftp-create-dirs
         else
-            exit 0
+            echo "Error: Invalid Raspberry Compiler Type!"
+            exit 1
         fi
     fi
+    exit 0
 fi
 
-if ! [ -f "$HOME/README.md" ]; then exit 0; fi
-
 # deploy Toolchain specific folder docs
-if [ "$COMPILER_TYPE" = "CROSS" ]; then
-    if [ "$RPI_TYPE" = "64" ]; then
-        FOLDER="Bonus Raspberry Pi GCC 64-Bit Toolchains/Raspberry Pi GCC 64-Bit Cross-Compiler Toolchains"
-
-        if [ "$FOLDER" != "" ]; then
-            curl -k  "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/README.md" --ftp-create-dirs
-        fi
-    else
+if [ "$FOLDER_TYPE" = "main" ] && [ -f "$HOME/main/README.md" ]; then
+    if [ "$TOOLCHAIN" = "cross" ]; then
         if [ "$RPIOS_TYPE" = "buster" ]; then
             FOLDER="Raspberry Pi GCC Cross-Compiler Toolchains/Buster"
-            curl -k  "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/README.md" --ftp-create-dirs
+            curl -k "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/main/README.md" --ftp-create-dirs
         elif [ "$RPIOS_TYPE" = "stretch" ]; then
             FOLDER="Raspberry Pi GCC Cross-Compiler Toolchains/Stretch"
-            curl -k  "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/README.md" --ftp-create-dirs
-        else            
+            curl -k "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/main/README.md" --ftp-create-dirs
+        else
+            echo "Error: Invalid Raspberry OS Type!"
             exit 1
         fi
-    fi
-elif [ "$COMPILER_TYPE" = "NATIVE" ]; then
-    if [ "$RPI_TYPE" = "64" ]; then
-        FOLDER="Bonus Raspberry Pi GCC 64-Bit Toolchains/Raspberry Pi GCC 64-Bit Native-Compiler Toolchains"
-        curl -k  "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/README.md" --ftp-create-dirs
-    else
+    elif [ "$TOOLCHAIN" = "native" ]; then
         if [ "$RPIOS_TYPE" = "buster" ]; then
             FOLDER="Raspberry Pi GCC Native-Compiler Toolchains/Buster"
-            curl -k  "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/README.md" --ftp-create-dirs
+            curl -k "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/main/README.md" --ftp-create-dirs
         elif [ "$RPIOS_TYPE" = "stretch" ]; then
             FOLDER="Raspberry Pi GCC Native-Compiler Toolchains/Stretch"
-            curl -k  "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/README.md" --ftp-create-dirs
-        else            
+            curl -k "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/main/README.md" --ftp-create-dirs
+        else
+            echo "Error: Invalid Raspberry OS Type!"
             exit 1
         fi
-    fi
-else
-    if [[ "$OS_TYPE" =~ ^("x86"|"x86_64")$ ]]; then
-        FOLDER="Exclusive-Experimental Toolchains/Desktop/$OS_TYPE"
-        curl -k  "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/README.md" --ftp-create-dirs
+    elif [ "$TOOLCHAIN" = "cross_64" ]; then
+        FOLDER="Bonus Raspberry Pi GCC 64-Bit Toolchains/Raspberry Pi GCC 64-Bit Cross-Compiler Toolchains"
+        curl -k "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/main/README.md" --ftp-create-dirs
+    elif [ "$TOOLCHAIN" = "native_64" ]; then
+        FOLDER="Bonus Raspberry Pi GCC 64-Bit Toolchains/Raspberry Pi GCC 64-Bit Native-Compiler Toolchains"
+        curl -k "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/main/README.md" --ftp-create-dirs
+    elif [ "$TOOLCHAIN" = "CLI" ]; then
+        FOLDER="CLI Base"
+        curl -k "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/main/README.md" --ftp-create-dirs
     else
-        exit 0
+        echo "Error: Invalid Main toolchain!"
+        exit 1
+    fi
+    exit 0
+fi
+
+if [ "$FOLDER_TYPE" = "experimental" ]; then
+    if [ -f "$HOME/experiment/README.md" ] && [[ "$RPI_TYPE" =~ ^("x86"|"x86_64")$ ]]; then
+        FOLDER="Exclusive-Experimental Toolchains/Desktop/$RPI_TYPE"
+        curl -k "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/experiment/README.md" --ftp-create-dirs
+    elif [ -f "$HOME/main/README.md" ]; then
+        FOLDER="Exclusive-Experimental Toolchains/Desktop"
+        curl -k "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/main/README.md" --ftp-create-dirs
+    elif [ -f "$HOME/base/README.md" ]; then
+        FOLDER="Exclusive-Experimental Toolchains"
+        curl -k "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/base/README.md" --ftp-create-dirs
+
+    else
+        echo "Warning: No Experimental docs found!"
+        exit 1
     fi
 fi
