Release v3.0.6: Major 64-bit env bug fixes and updates
- Fixed incorrect binary download links in CI bash scripts.
- Updated CI scripts to only allow >= 8.3.0 GCC versions.
- Replaced missing RPI_TYPE variable with FOLDER_VERSION.
- Removed 8.3.0 workflow from native builds.
- Updated Docs links.
- Added Github Sponser.

diff --git a/build-scripts/CI/CICTB_64b b/build-scripts/CI/CICTB_64b
--- a/build-scripts/CI/CICTB_64b
+++ b/build-scripts/CI/CICTB_64b
@@ -69,6 +69,12 @@ else
 	exit
 fi
 
+# exit if GCC < 8.3.0 for buster
+if [ "$RPIOS_TYPE" = "buster" ] && [ "$GCC_VERSION" \< "8.3.0" ]; then
+	echo "Invalid GCC for buster: $GCC_VERSION!"
+	exit
+fi
+
 #collect build directory if not defined
 if [ "$BUILDDIR" = "" ]; then
 	#select temp directory
@@ -96,8 +102,16 @@ if [ "$FOLDER_VERSION" != "64" ]; then exit 1; fi
 if [ "$BUILDDIR" = "" ]; then exit 1; fi
 if [ "$LANGUAGES" = "" ]; then exit 1; fi
 
-URL="https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/CLI%20Base"
-if [ "$RPI_TYPE" = "64" ]; then URL="$URL/64/GCC%20$GCCBASE_VERSION/"; fi
+URL="https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/CLI%20Base/64"
+
+if [ "$RPIOS_TYPE" = "buster" ]; then
+	URL="$URL/Buster/GCC%20$GCCBASE_VERSION/"
+elif [ "$RPIOS_TYPE" = "stretch" ]; then
+	URL="$URL/Stretch/GCC%20$GCCBASE_VERSION/"
+else
+	echo "Missing RPIOS_TYPE parameter!"
+	exit 1
+fi
 
 echo "Downloading and Setting up build directories"
 #setup paths
@@ -112,9 +126,9 @@ mkdir -p "$INSTALLDIR"
 cd "$DOWNLOADDIR" || exit
 
 #download binaries if not found
-if [ ! -f "cross-gcc-$GCCBASE_VERSION-pi_$RPI_TYPE.tar.gz" ]; then
-	wget -q --no-check-certificate "${URL}cross-gcc-$GCCBASE_VERSION-pi_$RPI_TYPE.tar.gz"
-	tar xf cross-gcc-$GCCBASE_VERSION-pi_$RPI_TYPE.tar.gz
+if [ ! -f "cross-gcc-$GCCBASE_VERSION-pi_$FOLDER_VERSION.tar.gz" ]; then
+	wget -q --no-check-certificate "${URL}cross-gcc-$GCCBASE_VERSION-pi_$FOLDER_VERSION.tar.gz"
+	tar xf cross-gcc-$GCCBASE_VERSION-pi_$FOLDER_VERSION.tar.gz
 	mv -v cross-pi-gcc-$GCCBASE_VERSION-$FOLDER_VERSION/* $INSTALLDIR
 	rm -rf cross-pi-gcc-$GCCBASE_VERSION-$FOLDER_VERSION
 	rm ./*.tar.*
@@ -171,7 +185,7 @@ echo "Done Building Cross GDB Binaries..."
 mv "$BUILDDIR"/cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION "$HOME"
 cd "$HOME" || exit
 #compress with maximum possible compression level.
-tar cf - cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 >cross-gcc-"$GCC_VERSION"-pi_"$RPI_TYPE".tar.gz
+tar cf - cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 >cross-gcc-"$GCC_VERSION"-pi_"$FOLDER_VERSION".tar.gz
 echo "Done Building Cross GCC $GCC_VERSION Binaries..."
 rm -rf "$HOME"/cross-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION
 
diff --git a/build-scripts/CI/CINTB_64b b/build-scripts/CI/CINTB_64b
--- a/build-scripts/CI/CINTB_64b
+++ b/build-scripts/CI/CINTB_64b
@@ -86,7 +86,21 @@ if [ "$BUILDDIR" = "" ]; then exit 1; fi
 if [ "$LANGUAGES" = "" ]; then exit 1; fi
 
 URL="https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Bonus%20Raspberry%20Pi%20GCC%2064-Bit%20Toolchains/Raspberry%20Pi%20GCC%2064-Bit%20Cross-Compiler%20Toolchains"
-if [ "$RPI_TYPE" = "64" ]; then URL="$URL/GCC%20$GCC_VERSION/"; fi
+
+if [ "$RPIOS_TYPE" = "buster" ]; then
+	URL="$URL/Buster/GCC%20$GCC_VERSION/"
+elif [ "$RPIOS_TYPE" = "stretch" ]; then
+	URL="$URL/Stretch/GCC%20$GCC_VERSION/"
+else
+	echo "Missing RPIOS_TYPE parameter!"
+	exit 1
+fi
+
+# exit if GCC < 9.0.0 for buster
+if [ "$RPIOS_TYPE" = "buster" ] && [ "$GCC_VERSION" \< "9.0.0" ]; then
+	echo "Invalid GCC for buster: $GCC_VERSION!"
+	exit
+fi
 
 echo "Downloading and Setting up build directories"
 #setup paths
@@ -96,9 +110,9 @@ mkdir -p "$DOWNLOADDIR"
 cd "$DOWNLOADDIR" || exit
 
 #download binaries if not found
-if [ ! -f "cross-gcc-$GCC_VERSION-pi_$RPI_TYPE.tar.gz" ]; then
-	wget "${URL}cross-gcc-$GCC_VERSION-pi_$RPI_TYPE.tar.gz"
-	tar xf cross-gcc-$GCC_VERSION-pi_$RPI_TYPE.tar.gz
+if [ ! -f "cross-gcc-$GCC_VERSION-pi_$FOLDER_VERSION.tar.gz" ]; then
+	wget "${URL}cross-gcc-$GCC_VERSION-pi_$FOLDER_VERSION.tar.gz"
+	tar xf cross-gcc-$GCC_VERSION-pi_$FOLDER_VERSION.tar.gz
 	mv cross-pi-gcc-$GCC_VERSION-$FOLDER_VERSION $BUILDDIR
 	rm ./*.tar.*
 fi
@@ -153,7 +167,7 @@ echo "Done Building Native GDB Binaries..."
 mv "$BUILDDIR"/native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION "$HOME"
 cd "$HOME" || exit
 #compress with maximum possible compression level.
-tar cf - native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 >native-gcc-"$GCC_VERSION"-pi_"$RPI_TYPE".tar.gz
+tar cf - native-pi-gcc-"$GCC_VERSION"-$FOLDER_VERSION | pigz -9 -p 32 >native-gcc-"$GCC_VERSION"-pi_"$FOLDER_VERSION".tar.gz
 echo "Done Building Native GCC $GCC_VERSION Binaries..."
 
 #clean path
