Refactor SF_deployer and SF_docs_deployer scripts
- Simplify and consolidate logic in SF_deployer
- Introduce deploy_file function for reusability
- Update folder structure to include Raspberry Pi 5
- Reorganize SF_docs_deployer with modular set_folder_and_filepath function
- Improve error handling and URL encoding
- Standardize deployment process across different toolchain types

diff --git a/utils/SF_docs_deployer b/utils/SF_docs_deployer
--- a/utils/SF_docs_deployer
+++ b/utils/SF_docs_deployer
@@ -35,7 +35,7 @@ helpfunction() {
     echo "Usage: $0 -t [Toolchain Type] -f [Folder type] -o [Target Pi OS type] -r [Raspberry Pi type] "
     echo -e "\t-t Toolchain Type?: (cross|native|cross_64|native_64|CLI)"
     echo -e "\t-f Upload Folder type?: (root|main|base|experimental)"
-    echo -e "\t-o Raspberry Pi OS type?: (bookworm|buster|bullseye)"
+    echo -e "\t-o Raspberry Pi OS type?: (buster|bullseye|bookworm)"
     echo -e "\t-r What's yours Target Raspberry Pi type?: (0-1|2-3|3+|x86|x86_64)"
     echo ""
     echo ""
@@ -71,105 +71,66 @@ fi
 echo "Doing $TOOLCHAIN with Folder: $FOLDER_TYPE, RASPBERRY: $RPI_TYPE AND OS: $RPIOS_TYPE!"
 
 # deploy root folder docs
-if [ "$FOLDER_TYPE" = "root" ]; then
-    if [ -f "$HOME/root/README.md" ]; then
-        curl -k -v "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/root/README.md" --ftp-create-dirs
-    else
-        echo "Error: No valid Root docs found!"
-        exit 1
-    fi
-    exit 0
+BASE_URL="sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers"
+FILEPATH=""
+
+set_folder_and_filepath() {
+    case "$FOLDER_TYPE" in
+        "root")
+            FOLDER=""
+            FILEPATH="$HOME/root/README.md"
+            ;;
+        "base")
+            case "$TOOLCHAIN" in
+                "CLI") FOLDER="CLI Base" ;;
+                "cross_64"|"native_64") FOLDER="Bonus Raspberry Pi GCC 64-Bit Toolchains" ;;
+                "cross") FOLDER="Raspberry Pi GCC Cross-Compiler Toolchains" ;;
+                "native") FOLDER="Raspberry Pi GCC Native-Compiler Toolchains" ;;
+                *) echo "Error: Invalid Raspberry Compiler Type!"; exit 1 ;;
+            esac
+            FILEPATH="$HOME/base/README.md"
+            ;;
+        "main")
+            case "$TOOLCHAIN" in
+                "cross"|"native")
+                    FOLDER="Raspberry Pi GCC ${TOOLCHAIN^}-Compiler Toolchains/${RPIOS_TYPE^}"
+                    ;;
+                "cross_64"|"native_64")
+                    FOLDER="Bonus Raspberry Pi GCC 64-Bit Toolchains/Raspberry Pi GCC 64-Bit ${TOOLCHAIN%-64^}-Compiler Toolchains/${RPIOS_TYPE^}"
+                    ;;
+                *) echo "Error: Invalid Main toolchain!"; exit 1 ;;
+            esac
+            FILEPATH="$HOME/main/README.md"
+            ;;
+        "experimental")
+            if [[ "$RPI_TYPE" =~ ^("x86"|"x86_64")$ ]]; then
+                FOLDER="Exclusive-Experimental Toolchains/Desktop/$RPI_TYPE"
+                FILEPATH="$HOME/experiment/README.md"
+            elif [ -f "$HOME/main/README.md" ]; then
+                FOLDER="Exclusive-Experimental Toolchains/Desktop"
+                FILEPATH="$HOME/main/README.md"
+            elif [ -f "$HOME/base/README.md" ]; then
+                FOLDER="Exclusive-Experimental Toolchains"
+                FILEPATH="$HOME/base/README.md"
+            else
+                echo "Warning: No Experimental docs found!"
+                exit 1
+            fi
+            ;;
+        *) echo "Error: Wrong folder!"; exit 1 ;;
+    esac
+}
+
+set_folder_and_filepath
+
+if [ ! -f "$FILEPATH" ]; then
+    echo "Error: No valid docs found at $FILEPATH!"
+    exit 1
 fi
 
-if [ "$FOLDER_TYPE" = "base" ] && [ -f "$HOME/base/README.md" ]; then
-    if [ "$TOOLCHAIN" = "CLI" ]; then
-        FOLDER="CLI Base"
-        curl -k -v "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/base/README.md" --ftp-create-dirs
-    elif [[ "$TOOLCHAIN" =~ ^("cross_64"|"native_64")$ ]]; then
-        FOLDER="Bonus Raspberry Pi GCC 64-Bit Toolchains"
-        curl -k -v "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/base/README.md" --ftp-create-dirs
-    else
-        if [ "$TOOLCHAIN" = "cross" ]; then
-            FOLDER="Raspberry Pi GCC Cross-Compiler Toolchains"
-            curl -k -v "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/base/README.md" --ftp-create-dirs
-        elif [ "$TOOLCHAIN" = "native" ]; then
-            FOLDER="Raspberry Pi GCC Native-Compiler Toolchains"
-            curl -k -v "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/base/README.md" --ftp-create-dirs
-        else
-            echo "Error: Invalid Raspberry Compiler Type!"
-            exit 0
-        fi
-    fi
-    exit 0
-fi
+URL="$BASE_URL/$FOLDER/"
+URL=$(printf "%s\n" "$URL" | sed 's/ /%20/g')
 
-# deploy Toolchain specific folder docs
-if [ "$FOLDER_TYPE" = "main" ] && [ -f "$HOME/main/README.md" ]; then
-    if [ "$TOOLCHAIN" = "cross" ]; then
-        if [ "$RPIOS_TYPE" = "buster" ]; then
-            FOLDER="Raspberry Pi GCC Cross-Compiler Toolchains/Buster"
-            curl -k -v "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/main/README.md" --ftp-create-dirs
-        elif [ "$RPIOS_TYPE" = "bullseye" ]; then
-            FOLDER="Raspberry Pi GCC Cross-Compiler Toolchains/Bullseye"
-        elif [ "$RPIOS_TYPE" = "bookworm" ]; then
-            FOLDER="Raspberry Pi GCC Cross-Compiler Toolchains/Bookworm"
-            curl -k -v "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/main/README.md" --ftp-create-dirs
-        else
-            echo "Error: Invalid Raspberry OS Type!"
-            exit 1
-        fi
-    elif [ "$TOOLCHAIN" = "native" ]; then
-        if [ "$RPIOS_TYPE" = "buster" ]; then
-            FOLDER="Raspberry Pi GCC Native-Compiler Toolchains/Buster"
-            curl -k -v "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/main/README.md" --ftp-create-dirs
-        elif [ "$RPIOS_TYPE" = "bullseye" ]; then
-            FOLDER="Raspberry Pi GCC Native-Compiler Toolchains/Bullseye"
-            curl -k -v "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/main/README.md" --ftp-create-dirs
-        elif [ "$RPIOS_TYPE" = "bookworm" ]; then
-            FOLDER="Raspberry Pi GCC Native-Compiler Toolchains/Bookworm"
-            curl -k -v "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/main/README.md" --ftp-create-dirs
-        else
-            echo "Error: Invalid Raspberry OS Type!"
-            exit 0
-        fi
-    elif [ "$TOOLCHAIN" = "cross_64" ]; then
-        if [ "$RPIOS_TYPE" = "buster" ]; then
-            FOLDER="Bonus Raspberry Pi GCC 64-Bit Toolchains/Raspberry Pi GCC 64-Bit Cross-Compiler Toolchains/Buster"
-        elif [ "$RPIOS_TYPE" = "bullseye" ]; then
-            FOLDER="Bonus Raspberry Pi GCC 64-Bit Toolchains/Raspberry Pi GCC 64-Bit Cross-Compiler Toolchains/Bullseye"
-        else
-            FOLDER="Bonus Raspberry Pi GCC 64-Bit Toolchains/Raspberry Pi GCC 64-Bit Cross-Compiler Toolchains/Bookworm"
-        fi
-        curl -k -v "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/main/README.md" --ftp-create-dirs
-    elif [ "$TOOLCHAIN" = "native_64" ]; then
-        if [ "$RPIOS_TYPE" = "buster" ]; then
-            FOLDER="Bonus Raspberry Pi GCC 64-Bit Toolchains/Raspberry Pi GCC 64-Bit Native-Compiler Toolchains/Buster"
-        elif [ "$RPIOS_TYPE" = "bullseye" ]; then
-            FOLDER="Bonus Raspberry Pi GCC 64-Bit Toolchains/Raspberry Pi GCC 64-Bit Native-Compiler Toolchains/Bullseye"
-        else
-            FOLDER="Bonus Raspberry Pi GCC 64-Bit Toolchains/Raspberry Pi GCC 64-Bit Native-Compiler Toolchains/Bookworm"
-        fi
-        curl -k -v "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/main/README.md" --ftp-create-dirs
-    else
-        echo "Error: Invalid Main toolchain!"
-        exit 1
-    fi
-    exit 0
-fi
+curl -k "$URL" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$FILEPATH" --ftp-create-dirs
 
-if [ "$FOLDER_TYPE" = "experimental" ]; then
-    if [ -f "$HOME/experiment/README.md" ] && [[ "$RPI_TYPE" =~ ^("x86"|"x86_64")$ ]]; then
-        FOLDER="Exclusive-Experimental Toolchains/Desktop/$RPI_TYPE"
-        curl -k -v "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/experiment/README.md" --ftp-create-dirs
-    elif [ -f "$HOME/main/README.md" ]; then
-        FOLDER="Exclusive-Experimental Toolchains/Desktop"
-        curl -k -v "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/main/README.md" --ftp-create-dirs
-    elif [ -f "$HOME/base/README.md" ]; then
-        FOLDER="Exclusive-Experimental Toolchains"
-        curl -k -v "sftp://frs.sourceforge.net/home/pfs/project/raspberry-pi-cross-compilers/$FOLDER/" -u "$USER_SFTP":"$PASSWORD_SFTP" -T "$HOME/base/README.md" --ftp-create-dirs
-
-    else
-        echo "Warning: No Experimental docs found!"
-        exit 1
-    fi
-fi
+exit 0
