Fixed syntax bug and line endings (Fixed #85)

diff --git a/utils/SSymlinker b/utils/SSymlinker
--- a/utils/SSymlinker
+++ b/utils/SSymlinker
@@ -27,80 +27,80 @@ set -eo pipefail # abort on errors
 
 # help function
 helpFunction() {
-	echo ""
-	echo ""
-	figlet -t -k -f /usr/share/figlet/standard.flf "SSymlinker: Safe Symlinker"
-	echo ""
-	echo "Usage: $0 -s SOURCE -d DESTINATION"
-	echo -e "\t-s Source directory/file."
-	echo -e "\t-d Destination directory/file."
-	exit 1 # Exit script after printing help
+    echo ""
+    echo ""
+    figlet -t -k -f /usr/share/figlet/standard.flf "SSymlinker: Safe Symlinker"
+    echo ""
+    echo "Usage: $0 -s SOURCE -d DESTINATION"
+    echo -e "\t-s Source directory/file."
+    echo -e "\t-d Destination directory/file."
+    exit 1 # Exit script after printing help
 }
 
 # get parameters
 while getopts "s:d:" opt; do
-	case "$opt" in
-	s) SOURCE="$OPTARG" ;;
-	d) DESTINATION="$OPTARG" ;;
-	?) helpFunction ;; # Print helpFunction in case parameter is non-existent
-	esac
+    case "$opt" in
+    s) SOURCE="$OPTARG" ;;
+    d) DESTINATION="$OPTARG" ;;
+    ?) helpFunction ;; # Print helpFunction in case parameter is non-existent
+    esac
 done
 
 # print helpFunction in case parameters are empty
 if [ -z "$SOURCE" ] || [ -z "$DESTINATION" ]; then
-	echo "Parameters are not valid. Aborting!"
-	helpFunction
+    echo "Parameters are not valid. Aborting!"
+    helpFunction
 fi
 
 # get valid destination
 if [[ ! -d $DESTINATION ]]; then
-	# get valid destination
-	if [[ ! -z $(basename $DESTINATION)]]; then
-		# get parent directory
-		DESTINATION=$(dirname $(readlink -f $DESTINATION))
-	else
-		DESTINATION=$(readlink -f "$DESTINATION")
-	fi
+    # get valid destination
+    if [[ ! -z $(basename $DESTINATION) ]]; then
+        # get parent directory
+        DESTINATION=$(dirname $(readlink -f $DESTINATION))
+    else
+        DESTINATION=$(readlink -f "$DESTINATION")
+    fi
 else
-	DESTINATION=$(readlink -f "$DESTINATION")
+    DESTINATION=$(readlink -f "$DESTINATION")
 fi
 if [[ ! -d $DESTINATION ]]; then
-	echo "$DESTINATION is not valid destination. Aborting!"
-	exit 1
+    echo "$DESTINATION is not valid destination. Aborting!"
+    exit 1
 fi
 
 # get valid source
 if [[ ! -d $SOURCE && ! -f $SOURCE ]]; then
-	echo "$SOURCE is not valid source file/directory. Aborting!"
-	exit 1
+    echo "$SOURCE is not valid source file/directory. Aborting!"
+    exit 1
 else
-	SOURCE=$(readlink -f "$SOURCE")
+    SOURCE=$(readlink -f "$SOURCE")
 fi
 
 # check if symlink already present or
 # SOURCE path and DESTINATION path are same
 if [[ $DESTINATION == $SOURCE || $DESTINATION == $(dirname $SOURCE) ]]; then
-	if [[ $DESTINATION == $(dirname $SOURCE) ]]; then
-		echo "Symlink already present, Aborting!"
-		exit 0
-	else
-		echo "SOURCE path and DESTINATION path cannot be same. Aborting!"
-		exit 1
-	fi
+    if [[ $DESTINATION == $(dirname $SOURCE) ]]; then
+        echo "Symlink already present, Aborting!"
+        exit 0
+    else
+        echo "SOURCE path and DESTINATION path cannot be same. Aborting!"
+        exit 1
+    fi
 fi
 
 # handle symlink creation
 if [[ ! -L "$DESTINATION/$(basename $SOURCE)" && -d "$DESTINATION/$(basename $SOURCE)" ]]; then
-	# a similar named non-empty folder already present at destination
-	sudo ln -s -f -v "$SOURCE/*" "$DESTINATION/$(basename $SOURCE)/*"
-	exit 0
+    # a similar named non-empty folder already present at destination
+    sudo ln -s -f -v "$SOURCE/*" "$DESTINATION/$(basename $SOURCE)/*"
+    exit 0
 elif [[ -f $DESTINATION ]]; then
-	# a similar named file already present a destination
-	read -t 3 -n 1 -p "Overwrite $DESTINATION (y/n)? " answer
-	[ -z "$answer" ] && answer=y
-	echo " "
+    # a similar named file already present a destination
+    read -t 3 -n 1 -p "Overwrite $DESTINATION (y/n)? " answer
+    [ -z "$answer" ] && answer=y
+    echo " "
 else
-	answer=y
+    answer=y
 fi
 
 # create symlink
